/*
 * Stub for class com.esoxjem.movieguide.favorites.FavoritesShare
 * Generated by Sapphire Compiler (sc).
 */
package com.esoxjem.movieguide.favorites.stubs;


public final class FavoritesShare_Stub extends com.esoxjem.movieguide.favorites.FavoritesShare implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public FavoritesShare_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of unfavorite(String)
    public void unfavorite(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.unfavorite( $param_String_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void com.esoxjem.movieguide.favorites.FavoritesShare.unfavorite(java.lang.String)";
                $__params.add($param_String_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of setMovieMap(String)
    public void setMovieMap(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setMovieMap( $param_String_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void com.esoxjem.movieguide.favorites.FavoritesShare.setMovieMap(java.lang.String)";
                $__params.add($param_String_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of isfavorite(String)
    public boolean isfavorite(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.isfavorite( $param_String_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boolean com.esoxjem.movieguide.favorites.FavoritesShare.isfavorite(java.lang.String)";
                $__params.add($param_String_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // Implementation of getMovieMap()
    public java.util.HashMap getMovieMap() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getMovieMap();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.HashMap com.esoxjem.movieguide.favorites.FavoritesShare.getMovieMap()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.HashMap) $__result);
    }

    // Implementation of PrintMsg()
    public void PrintMsg() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.PrintMsg();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void com.esoxjem.movieguide.favorites.FavoritesShare.PrintMsg()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
