/*
 * Stub for class com.esoxjem.movieguide.favorites.FavoritesStore
 * Generated by Sapphire Compiler (sc).
 */
package com.esoxjem.movieguide.favorites.stubs;


public final class FavoritesStore_Stub extends com.esoxjem.movieguide.favorites.FavoritesStore implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public FavoritesStore_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of unfavorite(String)
    public void unfavorite(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.unfavorite( $param_String_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void com.esoxjem.movieguide.favorites.FavoritesStore.unfavorite(java.lang.String)";
                $__params.add($param_String_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of setFavorite(String, String)
    public void setFavorite(java.lang.String $param_String_1, java.lang.String $param_String_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setFavorite( $param_String_1,  $param_String_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void com.esoxjem.movieguide.favorites.FavoritesStore.setFavorite(java.lang.String,java.lang.String)";
                $__params.add($param_String_1);
                $__params.add($param_String_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of isFavorite(String)
    public boolean isFavorite(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.isFavorite( $param_String_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boolean com.esoxjem.movieguide.favorites.FavoritesStore.isFavorite(java.lang.String)";
                $__params.add($param_String_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // Implementation of getFavorites()
    public java.util.List getFavorites()
            throws java.io.IOException {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getFavorites();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<java.lang.String> com.esoxjem.movieguide.favorites.FavoritesStore.getFavorites() throws java.io.IOException";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }
}
