/*
 * Stub for class sapphire.policy.atleastoncerpc.AtLeastOnceRPCPolicy.AtLeastOnceRPCGroupPolicy
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.stubexample;


import sapphire.common.AppObject;
import sapphire.policy.SapphirePolicy;


public final class AtLeastOnceRPCPolicy$AtLeastOnceRPCGroupPolicy_Stub extends sapphire.policy.atleastoncerpc.AtLeastOnceRPCPolicy.AtLeastOnceRPCGroupPolicy implements sapphire.kernel.common.KernelObjectStub {

    sapphire.kernel.common.KernelOID $__oid = null;
    java.net.InetSocketAddress $__hostname = null;
    AppObject appObject = null;
    SapphirePolicy.SapphireClientPolicy $__nextClientPolicy = null;

    public AtLeastOnceRPCPolicy$AtLeastOnceRPCGroupPolicy_Stub(sapphire.kernel.common.KernelOID oid) {
        this.$__oid = oid;
    }

    public sapphire.kernel.common.KernelOID $__getKernelOID() {
        return this.$__oid;
    }

    public java.net.InetSocketAddress $__getHostname() {
        return this.$__hostname;
    }

    public void $__updateHostname(java.net.InetSocketAddress hostname) {
        this.$__hostname = hostname;
    }

    public void $__setNextClientPolicy(SapphirePolicy.SapphireClientPolicy clientPolicy) {
        this.$__nextClientPolicy = clientPolicy;
    }

    public AppObject $__getAppObject() {
        return this.appObject;
    }

    public Object $__makeKernelRPC(String method, java.util.ArrayList<Object> params) throws java.rmi.RemoteException, Exception {
        if ($__nextClientPolicy != null) {
            return $__nextClientPolicy.onRPC(method, params);
        }

        sapphire.kernel.common.KernelRPC rpc = new sapphire.kernel.common.KernelRPC($__oid, method, params);
        try {
            return sapphire.kernel.common.GlobalKernelReferences.nodeServer.getKernelClient().makeKernelRPC(this, rpc);
        } catch (sapphire.kernel.common.KernelObjectNotFoundException e) {
            throw new java.rmi.RemoteException();
        }
    }

    @Override
    public boolean equals(Object obj) {
        AtLeastOnceRPCPolicy$AtLeastOnceRPCGroupPolicy_Stub other = (AtLeastOnceRPCPolicy$AtLeastOnceRPCGroupPolicy_Stub) obj;
        if (! other.$__oid.equals($__oid))
            return false;
        return true;
    }
    @Override
    public int hashCode() {
        return $__oid.getID();
    }


    // Implementation of removeServer(SapphirePolicy.SapphireServerPolicy)
    public void removeServer(SapphirePolicy.SapphireServerPolicy $param_SapphirePolicy$SapphireServerPolicy_1)
            throws java.rmi.RemoteException {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.DefaultSapphirePolicy$DefaultGroupPolicy.removeServer(sapphire.policy.SapphirePolicy$SapphireServerPolicy) throws java.rmi.RemoteException";
        $__params.add($param_SapphirePolicy$SapphireServerPolicy_1);
        Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (RuntimeException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    // Implementation of onRefRequest()
    public SapphirePolicy.SapphireServerPolicy onRefRequest()
            throws java.rmi.RemoteException {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public sapphire.policy.SapphirePolicy$SapphireServerPolicy sapphire.policy.DefaultSapphirePolicyUpcallImpl$DefaultSapphireGroupPolicyUpcallImpl.onRefRequest() throws java.rmi.RemoteException";
        Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (RuntimeException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        return ((SapphirePolicy.SapphireServerPolicy) $__result);
    }

    // Implementation of onFailure(SapphirePolicy.SapphireServerPolicy)
    public void onFailure(SapphirePolicy.SapphireServerPolicy $param_SapphirePolicy$SapphireServerPolicy_1)
            throws java.rmi.RemoteException {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.DefaultSapphirePolicy$DefaultGroupPolicy.onFailure(sapphire.policy.SapphirePolicy$SapphireServerPolicy) throws java.rmi.RemoteException";
        $__params.add($param_SapphirePolicy$SapphireServerPolicy_1);
        Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (RuntimeException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    // Implementation of onDestroy()
    public void onDestroy()
            throws java.rmi.RemoteException {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public synchronized void sapphire.policy.DefaultSapphirePolicy$DefaultGroupPolicy.onDestroy() throws java.rmi.RemoteException";
        Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (RuntimeException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    // Implementation of onCreate(SapphirePolicy.SapphireServerPolicy, Annotation[])
    public void onCreate(SapphirePolicy.SapphireServerPolicy $param_SapphirePolicy$SapphireServerPolicy_1, java.lang.annotation.Annotation[] $param_arrayOf_Annotation_2)
            throws java.rmi.RemoteException {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.DefaultSapphirePolicy$DefaultGroupPolicy.onCreate(sapphire.policy.SapphirePolicy$SapphireServerPolicy,java.lang.annotation.Annotation[]) throws java.rmi.RemoteException";
        $__params.add($param_SapphirePolicy$SapphireServerPolicy_1);
        $__params.add($param_arrayOf_Annotation_2);
        Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (RuntimeException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    // Implementation of getServers()
    public java.util.ArrayList getServers()
            throws java.rmi.RemoteException {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public java.util.ArrayList<sapphire.policy.SapphirePolicy$SapphireServerPolicy> sapphire.policy.DefaultSapphirePolicy$DefaultGroupPolicy.getServers() throws java.rmi.RemoteException";
        Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (RuntimeException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        return ((java.util.ArrayList) $__result);
    }

    // Implementation of getAppConfigAnnotation()
    public java.lang.annotation.Annotation[] getAppConfigAnnotation() {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public java.lang.annotation.Annotation[] sapphire.policy.DefaultSapphirePolicyUpcallImpl$DefaultSapphireGroupPolicyUpcallImpl.getAppConfigAnnotation()";
        Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (RuntimeException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        return ((java.lang.annotation.Annotation[]) $__result);
    }

    // Implementation of addServer(SapphirePolicy.SapphireServerPolicy)
    public void addServer(SapphirePolicy.SapphireServerPolicy $param_SapphirePolicy$SapphireServerPolicy_1)
            throws java.rmi.RemoteException {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public synchronized void sapphire.policy.DefaultSapphirePolicy$DefaultGroupPolicy.addServer(sapphire.policy.SapphirePolicy$SapphireServerPolicy) throws java.rmi.RemoteException";
        $__params.add($param_SapphirePolicy$SapphireServerPolicy_1);
        Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (RuntimeException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    // Implementation of $__initialize(String, ArrayList)
    public void $__initialize(String $param_String_1, java.util.ArrayList $param_ArrayList_2) {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.DefaultSapphirePolicyUpcallImpl$DefaultSapphireGroupPolicyUpcallImpl.$__initialize(java.lang.String,java.util.ArrayList<java.lang.Object>)";
        $__params.add($param_String_1);
        $__params.add($param_ArrayList_2);
        Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (RuntimeException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
