// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToApp.proto

package sapphire.kernel.app;

public interface AcquireRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sapphire.kernel.app.AcquireRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string sId = 1;</code>
   */
  java.lang.String getSId();
  /**
   * <code>optional string sId = 1;</code>
   */
  com.google.protobuf.ByteString
      getSIdBytes();

  /**
   * <code>optional string dmClientRmiEndPoint = 2;</code>
   */
  java.lang.String getDmClientRmiEndPoint();
  /**
   * <code>optional string dmClientRmiEndPoint = 2;</code>
   */
  com.google.protobuf.ByteString
      getDmClientRmiEndPointBytes();
}
