// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToApp.proto

package sapphire.kernel.app;

/**
 * Protobuf type {@code sapphire.kernel.app.AcquireResponse}
 */
public  final class AcquireResponse extends
    com.google.protobuf.GeneratedMessageLite<
        AcquireResponse, AcquireResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:sapphire.kernel.app.AcquireResponse)
    AcquireResponseOrBuilder {
  private AcquireResponse() {
    objectStream_ = com.google.protobuf.ByteString.EMPTY;
    clientId_ = "";
  }
  public static final int OBJECTSTREAM_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString objectStream_;
  /**
   * <code>optional bytes objectStream = 1;</code>
   */
  public com.google.protobuf.ByteString getObjectStream() {
    return objectStream_;
  }
  /**
   * <code>optional bytes objectStream = 1;</code>
   */
  private void setObjectStream(com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    objectStream_ = value;
  }
  /**
   * <code>optional bytes objectStream = 1;</code>
   */
  private void clearObjectStream() {
    
    objectStream_ = getDefaultInstance().getObjectStream();
  }

  public static final int CLIENTID_FIELD_NUMBER = 2;
  private java.lang.String clientId_;
  /**
   * <code>optional string clientId = 2;</code>
   */
  public java.lang.String getClientId() {
    return clientId_;
  }
  /**
   * <code>optional string clientId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(clientId_);
  }
  /**
   * <code>optional string clientId = 2;</code>
   */
  private void setClientId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    clientId_ = value;
  }
  /**
   * <code>optional string clientId = 2;</code>
   */
  private void clearClientId() {
    
    clientId_ = getDefaultInstance().getClientId();
  }
  /**
   * <code>optional string clientId = 2;</code>
   */
  private void setClientIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    clientId_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!objectStream_.isEmpty()) {
      output.writeBytes(1, objectStream_);
    }
    if (!clientId_.isEmpty()) {
      output.writeString(2, getClientId());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!objectStream_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, objectStream_);
    }
    if (!clientId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getClientId());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static sapphire.kernel.app.AcquireResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.kernel.app.AcquireResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.kernel.app.AcquireResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.kernel.app.AcquireResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.kernel.app.AcquireResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.AcquireResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.kernel.app.AcquireResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.AcquireResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.kernel.app.AcquireResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.AcquireResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sapphire.kernel.app.AcquireResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code sapphire.kernel.app.AcquireResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        sapphire.kernel.app.AcquireResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:sapphire.kernel.app.AcquireResponse)
      sapphire.kernel.app.AcquireResponseOrBuilder {
    // Construct using sapphire.kernel.app.AcquireResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional bytes objectStream = 1;</code>
     */
    public com.google.protobuf.ByteString getObjectStream() {
      return instance.getObjectStream();
    }
    /**
     * <code>optional bytes objectStream = 1;</code>
     */
    public Builder setObjectStream(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setObjectStream(value);
      return this;
    }
    /**
     * <code>optional bytes objectStream = 1;</code>
     */
    public Builder clearObjectStream() {
      copyOnWrite();
      instance.clearObjectStream();
      return this;
    }

    /**
     * <code>optional string clientId = 2;</code>
     */
    public java.lang.String getClientId() {
      return instance.getClientId();
    }
    /**
     * <code>optional string clientId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      return instance.getClientIdBytes();
    }
    /**
     * <code>optional string clientId = 2;</code>
     */
    public Builder setClientId(
        java.lang.String value) {
      copyOnWrite();
      instance.setClientId(value);
      return this;
    }
    /**
     * <code>optional string clientId = 2;</code>
     */
    public Builder clearClientId() {
      copyOnWrite();
      instance.clearClientId();
      return this;
    }
    /**
     * <code>optional string clientId = 2;</code>
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setClientIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sapphire.kernel.app.AcquireResponse)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new sapphire.kernel.app.AcquireResponse();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        sapphire.kernel.app.AcquireResponse other = (sapphire.kernel.app.AcquireResponse) arg1;
        objectStream_ = visitor.visitByteString(objectStream_ != com.google.protobuf.ByteString.EMPTY, objectStream_,
            other.objectStream_ != com.google.protobuf.ByteString.EMPTY, other.objectStream_);
        clientId_ = visitor.visitString(!clientId_.isEmpty(), clientId_,
            !other.clientId_.isEmpty(), other.clientId_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {

                objectStream_ = input.readBytes();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                clientId_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (sapphire.kernel.app.AcquireResponse.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sapphire.kernel.app.AcquireResponse)
  private static final sapphire.kernel.app.AcquireResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AcquireResponse();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static sapphire.kernel.app.AcquireResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AcquireResponse> PARSER;

  public static com.google.protobuf.Parser<AcquireResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

