// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToApp.proto

package sapphire.kernel.app;

public interface AttachRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sapphire.kernel.app.AttachRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string url = 1;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>optional string url = 1;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>optional string dmClientRmiEndPoint = 2;</code>
   */
  java.lang.String getDmClientRmiEndPoint();
  /**
   * <code>optional string dmClientRmiEndPoint = 2;</code>
   */
  com.google.protobuf.ByteString
      getDmClientRmiEndPointBytes();
}
