// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToApp.proto

package sapphire.kernel.app;

/**
 * Protobuf type {@code sapphire.kernel.app.AttachRequest}
 */
public  final class AttachRequest extends
    com.google.protobuf.GeneratedMessageLite<
        AttachRequest, AttachRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:sapphire.kernel.app.AttachRequest)
    AttachRequestOrBuilder {
  private AttachRequest() {
    url_ = "";
    dmClientRmiEndPoint_ = "";
  }
  public static final int URL_FIELD_NUMBER = 1;
  private java.lang.String url_;
  /**
   * <code>optional string url = 1;</code>
   */
  public java.lang.String getUrl() {
    return url_;
  }
  /**
   * <code>optional string url = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(url_);
  }
  /**
   * <code>optional string url = 1;</code>
   */
  private void setUrl(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    url_ = value;
  }
  /**
   * <code>optional string url = 1;</code>
   */
  private void clearUrl() {
    
    url_ = getDefaultInstance().getUrl();
  }
  /**
   * <code>optional string url = 1;</code>
   */
  private void setUrlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    url_ = value.toStringUtf8();
  }

  public static final int DMCLIENTRMIENDPOINT_FIELD_NUMBER = 2;
  private java.lang.String dmClientRmiEndPoint_;
  /**
   * <code>optional string dmClientRmiEndPoint = 2;</code>
   */
  public java.lang.String getDmClientRmiEndPoint() {
    return dmClientRmiEndPoint_;
  }
  /**
   * <code>optional string dmClientRmiEndPoint = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDmClientRmiEndPointBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(dmClientRmiEndPoint_);
  }
  /**
   * <code>optional string dmClientRmiEndPoint = 2;</code>
   */
  private void setDmClientRmiEndPoint(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    dmClientRmiEndPoint_ = value;
  }
  /**
   * <code>optional string dmClientRmiEndPoint = 2;</code>
   */
  private void clearDmClientRmiEndPoint() {
    
    dmClientRmiEndPoint_ = getDefaultInstance().getDmClientRmiEndPoint();
  }
  /**
   * <code>optional string dmClientRmiEndPoint = 2;</code>
   */
  private void setDmClientRmiEndPointBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    dmClientRmiEndPoint_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!url_.isEmpty()) {
      output.writeString(1, getUrl());
    }
    if (!dmClientRmiEndPoint_.isEmpty()) {
      output.writeString(2, getDmClientRmiEndPoint());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!url_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getUrl());
    }
    if (!dmClientRmiEndPoint_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getDmClientRmiEndPoint());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static sapphire.kernel.app.AttachRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.kernel.app.AttachRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.kernel.app.AttachRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.kernel.app.AttachRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.kernel.app.AttachRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.AttachRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.kernel.app.AttachRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.AttachRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.kernel.app.AttachRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.AttachRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sapphire.kernel.app.AttachRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code sapphire.kernel.app.AttachRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        sapphire.kernel.app.AttachRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:sapphire.kernel.app.AttachRequest)
      sapphire.kernel.app.AttachRequestOrBuilder {
    // Construct using sapphire.kernel.app.AttachRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string url = 1;</code>
     */
    public java.lang.String getUrl() {
      return instance.getUrl();
    }
    /**
     * <code>optional string url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      return instance.getUrlBytes();
    }
    /**
     * <code>optional string url = 1;</code>
     */
    public Builder setUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setUrl(value);
      return this;
    }
    /**
     * <code>optional string url = 1;</code>
     */
    public Builder clearUrl() {
      copyOnWrite();
      instance.clearUrl();
      return this;
    }
    /**
     * <code>optional string url = 1;</code>
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUrlBytes(value);
      return this;
    }

    /**
     * <code>optional string dmClientRmiEndPoint = 2;</code>
     */
    public java.lang.String getDmClientRmiEndPoint() {
      return instance.getDmClientRmiEndPoint();
    }
    /**
     * <code>optional string dmClientRmiEndPoint = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDmClientRmiEndPointBytes() {
      return instance.getDmClientRmiEndPointBytes();
    }
    /**
     * <code>optional string dmClientRmiEndPoint = 2;</code>
     */
    public Builder setDmClientRmiEndPoint(
        java.lang.String value) {
      copyOnWrite();
      instance.setDmClientRmiEndPoint(value);
      return this;
    }
    /**
     * <code>optional string dmClientRmiEndPoint = 2;</code>
     */
    public Builder clearDmClientRmiEndPoint() {
      copyOnWrite();
      instance.clearDmClientRmiEndPoint();
      return this;
    }
    /**
     * <code>optional string dmClientRmiEndPoint = 2;</code>
     */
    public Builder setDmClientRmiEndPointBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDmClientRmiEndPointBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sapphire.kernel.app.AttachRequest)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new sapphire.kernel.app.AttachRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        sapphire.kernel.app.AttachRequest other = (sapphire.kernel.app.AttachRequest) arg1;
        url_ = visitor.visitString(!url_.isEmpty(), url_,
            !other.url_.isEmpty(), other.url_);
        dmClientRmiEndPoint_ = visitor.visitString(!dmClientRmiEndPoint_.isEmpty(), dmClientRmiEndPoint_,
            !other.dmClientRmiEndPoint_.isEmpty(), other.dmClientRmiEndPoint_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                url_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                dmClientRmiEndPoint_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (sapphire.kernel.app.AttachRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sapphire.kernel.app.AttachRequest)
  private static final sapphire.kernel.app.AttachRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AttachRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static sapphire.kernel.app.AttachRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AttachRequest> PARSER;

  public static com.google.protobuf.Parser<AttachRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

