// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToApp.proto

package sapphire.kernel.app;

public interface DeleteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sapphire.kernel.app.DeleteResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional bool status = 1;</code>
   */
  boolean getStatus();
}
