// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToApp.proto

package sapphire.kernel.app;

public interface DeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sapphire.kernel.app.DeleteRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string sId = 1;</code>
   */
  java.lang.String getSId();
  /**
   * <code>optional string sId = 1;</code>
   */
  com.google.protobuf.ByteString
      getSIdBytes();
}
