// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToApp.proto

package sapphire.kernel.app;

public interface InvokeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sapphire.kernel.app.InvokeResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional bytes objectStream = 1;</code>
   */
  com.google.protobuf.ByteString getObjectStream();
}
