// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToApp.proto

package sapphire.kernel.app;

public interface ReleaseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sapphire.kernel.app.ReleaseRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string sId = 1;</code>
   */
  java.lang.String getSId();
  /**
   * <code>optional string sId = 1;</code>
   */
  com.google.protobuf.ByteString
      getSIdBytes();

  /**
   * <code>optional string clientId = 2;</code>
   */
  java.lang.String getClientId();
  /**
   * <code>optional string clientId = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
