#!/usr/bin/python

#
# This script is for generating application stub files for the cloud env (linux host). It requires the app jar file generated by JDK tool chain. 
# It is different from another file generate_app_stubs.py, which generates application stub files for the device env, which in turn requires dex file generated by Android SDK/Android Studio tool chain.
#
# WARNING:
# This script is going to be deprecated. Please use the script inside
# example apps to generate app stubs. For example, use 
# sapphire/examples/hanksTodo/generators/generate_app_stubs_on_hosts.py
# to generate app stubs for hanksTodo.

import os, sys
import subprocess
from apps.todo import *
#from apps.minnietwitter import *

if __name__ == '__main__':

    sapphire_home = os.path.normpath(os.path.join(os.path.realpath(__file__), '../..'))
 
    cp_app = "%s/sapphire/examples/%s/build/intermediates/packaged/release/classes.jar"%(sapphire_home, app_name)
    cp_sapphire = sapphire_home + '/sapphire/sapphire-core/build/libs/sapphire-core.jar'
    cp_harmony = sapphire_home + '/sapphire/dependencies/apache.harmony/build/libs/apache.harmony.jar'
    
    cmd = ['java', '-cp',  cp_app + ':' + cp_sapphire + ':' + cp_harmony, 'sapphire.compiler.StubGenerator', sapphire_home + inFolder, package, sapphire_home + outFolder]

    p1 = subprocess.Popen(cmd)
    p1.wait()

    print("Done!")
