// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TodoList.proto

package hankstodo_app

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TodoList struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoList) Reset()         { *m = TodoList{} }
func (m *TodoList) String() string { return proto.CompactTextString(m) }
func (*TodoList) ProtoMessage()    {}
func (*TodoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_TodoList_46ffe27cc09abcf5, []int{0}
}
func (m *TodoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoList.Unmarshal(m, b)
}
func (m *TodoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoList.Marshal(b, m, deterministic)
}
func (dst *TodoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoList.Merge(dst, src)
}
func (m *TodoList) XXX_Size() int {
	return xxx_messageInfo_TodoList.Size(m)
}
func (m *TodoList) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoList.DiscardUnknown(m)
}

var xxx_messageInfo_TodoList proto.InternalMessageInfo

func (m *TodoList) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *TodoList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type InAddToDo struct {
	Arg0                 string   `protobuf:"bytes,1,opt,name=arg0,proto3" json:"arg0,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InAddToDo) Reset()         { *m = InAddToDo{} }
func (m *InAddToDo) String() string { return proto.CompactTextString(m) }
func (*InAddToDo) ProtoMessage()    {}
func (*InAddToDo) Descriptor() ([]byte, []int) {
	return fileDescriptor_TodoList_46ffe27cc09abcf5, []int{1}
}
func (m *InAddToDo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InAddToDo.Unmarshal(m, b)
}
func (m *InAddToDo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InAddToDo.Marshal(b, m, deterministic)
}
func (dst *InAddToDo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InAddToDo.Merge(dst, src)
}
func (m *InAddToDo) XXX_Size() int {
	return xxx_messageInfo_InAddToDo.Size(m)
}
func (m *InAddToDo) XXX_DiscardUnknown() {
	xxx_messageInfo_InAddToDo.DiscardUnknown(m)
}

var xxx_messageInfo_InAddToDo proto.InternalMessageInfo

func (m *InAddToDo) GetArg0() string {
	if m != nil {
		return m.Arg0
	}
	return ""
}

type OutAddToDo struct {
	Arg0                 string   `protobuf:"bytes,1,opt,name=arg0,proto3" json:"arg0,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutAddToDo) Reset()         { *m = OutAddToDo{} }
func (m *OutAddToDo) String() string { return proto.CompactTextString(m) }
func (*OutAddToDo) ProtoMessage()    {}
func (*OutAddToDo) Descriptor() ([]byte, []int) {
	return fileDescriptor_TodoList_46ffe27cc09abcf5, []int{2}
}
func (m *OutAddToDo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutAddToDo.Unmarshal(m, b)
}
func (m *OutAddToDo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutAddToDo.Marshal(b, m, deterministic)
}
func (dst *OutAddToDo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutAddToDo.Merge(dst, src)
}
func (m *OutAddToDo) XXX_Size() int {
	return xxx_messageInfo_OutAddToDo.Size(m)
}
func (m *OutAddToDo) XXX_DiscardUnknown() {
	xxx_messageInfo_OutAddToDo.DiscardUnknown(m)
}

var xxx_messageInfo_OutAddToDo proto.InternalMessageInfo

func (m *OutAddToDo) GetArg0() string {
	if m != nil {
		return m.Arg0
	}
	return ""
}

func init() {
	proto.RegisterType((*TodoList)(nil), "hankstodo_app.TodoList")
	proto.RegisterType((*InAddToDo)(nil), "hankstodo_app.inAddToDo")
	proto.RegisterType((*OutAddToDo)(nil), "hankstodo_app.outAddToDo")
}

func init() { proto.RegisterFile("TodoList.proto", fileDescriptor_TodoList_46ffe27cc09abcf5) }

var fileDescriptor_TodoList_46ffe27cc09abcf5 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0b, 0xc9, 0x4f, 0xc9,
	0xf7, 0xc9, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcd, 0x48, 0xcc, 0xcb,
	0x2e, 0x2e, 0xc9, 0x4f, 0xc9, 0x8f, 0x4f, 0x2c, 0x28, 0x50, 0x32, 0xe0, 0xe2, 0x80, 0x29, 0x10,
	0x12, 0xe0, 0x62, 0x2e, 0xce, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x85,
	0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0, 0x42, 0x60, 0xb6, 0x92, 0x3c, 0x17,
	0x67, 0x66, 0x9e, 0x63, 0x4a, 0x4a, 0x48, 0xbe, 0x4b, 0x3e, 0x48, 0x41, 0x62, 0x51, 0xba, 0x01,
	0x54, 0x0f, 0x98, 0xad, 0xa4, 0xc0, 0xc5, 0x95, 0x5f, 0x5a, 0x82, 0x47, 0x85, 0x13, 0x3f, 0x17,
	0xc2, 0x15, 0x7a, 0x89, 0x05, 0x05, 0x49, 0x6c, 0x60, 0xb7, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x53, 0x7c, 0x08, 0x27, 0xad, 0x00, 0x00, 0x00,
}
