// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TodoListManager.proto

package hankstodo_app

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TodoListManager struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoListManager) Reset()         { *m = TodoListManager{} }
func (m *TodoListManager) String() string { return proto.CompactTextString(m) }
func (*TodoListManager) ProtoMessage()    {}
func (*TodoListManager) Descriptor() ([]byte, []int) {
	return fileDescriptor_TodoListManager_a8a659fe63a92c39, []int{0}
}
func (m *TodoListManager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoListManager.Unmarshal(m, b)
}
func (m *TodoListManager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoListManager.Marshal(b, m, deterministic)
}
func (dst *TodoListManager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoListManager.Merge(dst, src)
}
func (m *TodoListManager) XXX_Size() int {
	return xxx_messageInfo_TodoListManager.Size(m)
}
func (m *TodoListManager) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoListManager.DiscardUnknown(m)
}

var xxx_messageInfo_TodoListManager proto.InternalMessageInfo

func (m *TodoListManager) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type NewTodo struct {
	Arg0                 string   `protobuf:"bytes,1,opt,name=arg0,proto3" json:"arg0,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTodo) Reset()         { *m = NewTodo{} }
func (m *NewTodo) String() string { return proto.CompactTextString(m) }
func (*NewTodo) ProtoMessage()    {}
func (*NewTodo) Descriptor() ([]byte, []int) {
	return fileDescriptor_TodoListManager_a8a659fe63a92c39, []int{1}
}
func (m *NewTodo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTodo.Unmarshal(m, b)
}
func (m *NewTodo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTodo.Marshal(b, m, deterministic)
}
func (dst *NewTodo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTodo.Merge(dst, src)
}
func (m *NewTodo) XXX_Size() int {
	return xxx_messageInfo_NewTodo.Size(m)
}
func (m *NewTodo) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTodo.DiscardUnknown(m)
}

var xxx_messageInfo_NewTodo proto.InternalMessageInfo

func (m *NewTodo) GetArg0() string {
	if m != nil {
		return m.Arg0
	}
	return ""
}

func init() {
	proto.RegisterType((*TodoListManager)(nil), "hankstodo_app.TodoListManager")
	proto.RegisterType((*NewTodo)(nil), "hankstodo_app.newTodo")
}

func init() {
	proto.RegisterFile("TodoListManager.proto", fileDescriptor_TodoListManager_a8a659fe63a92c39)
}

var fileDescriptor_TodoListManager_a8a659fe63a92c39 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0d, 0xc9, 0x4f, 0xc9,
	0xf7, 0xc9, 0x2c, 0x2e, 0xf1, 0x4d, 0xcc, 0x4b, 0x4c, 0x4f, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0xcd, 0x48, 0xcc, 0xcb, 0x2e, 0x2e, 0xc9, 0x4f, 0xc9, 0x8f, 0x4f, 0x2c, 0x28,
	0x50, 0x52, 0xe6, 0xe2, 0x47, 0x53, 0x27, 0x24, 0xc0, 0xc5, 0x5c, 0x9c, 0x99, 0x22, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x62, 0x2a, 0xc9, 0x72, 0xb1, 0xe7, 0xa5, 0x96, 0x83, 0xd4, 0x09,
	0x09, 0x71, 0xb1, 0x24, 0x16, 0xa5, 0x1b, 0x40, 0x65, 0xc1, 0x6c, 0x27, 0x7e, 0x2e, 0x84, 0xa1,
	0x7a, 0x89, 0x05, 0x05, 0x49, 0x6c, 0x60, 0xab, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x37,
	0x92, 0xb9, 0x21, 0x83, 0x00, 0x00, 0x00,
}
