// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TodoListManager.proto

package hankstodo.app;

public final class TodoListManagerOuterClass {
  private TodoListManagerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface TodoListManagerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hankstodo_app.TodoListManager)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string sid = 1;</code>
     */
    java.lang.String getSid();
    /**
     * <code>optional string sid = 1;</code>
     */
    com.google.protobuf.ByteString
        getSidBytes();
  }
  /**
   * Protobuf type {@code hankstodo_app.TodoListManager}
   */
  public  static final class TodoListManager extends
      com.google.protobuf.GeneratedMessageLite<
          TodoListManager, TodoListManager.Builder> implements
      // @@protoc_insertion_point(message_implements:hankstodo_app.TodoListManager)
      TodoListManagerOrBuilder {
    private TodoListManager() {
      sid_ = "";
    }
    public static final int SID_FIELD_NUMBER = 1;
    private java.lang.String sid_;
    /**
     * <code>optional string sid = 1;</code>
     */
    public java.lang.String getSid() {
      return sid_;
    }
    /**
     * <code>optional string sid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sid_);
    }
    /**
     * <code>optional string sid = 1;</code>
     */
    private void setSid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sid_ = value;
    }
    /**
     * <code>optional string sid = 1;</code>
     */
    private void clearSid() {
      
      sid_ = getDefaultInstance().getSid();
    }
    /**
     * <code>optional string sid = 1;</code>
     */
    private void setSidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sid_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!sid_.isEmpty()) {
        output.writeString(1, getSid());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!sid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSid());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static hankstodo.app.TodoListManagerOuterClass.TodoListManager parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static hankstodo.app.TodoListManagerOuterClass.TodoListManager parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static hankstodo.app.TodoListManagerOuterClass.TodoListManager parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static hankstodo.app.TodoListManagerOuterClass.TodoListManager parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static hankstodo.app.TodoListManagerOuterClass.TodoListManager parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListManagerOuterClass.TodoListManager parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static hankstodo.app.TodoListManagerOuterClass.TodoListManager parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListManagerOuterClass.TodoListManager parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static hankstodo.app.TodoListManagerOuterClass.TodoListManager parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListManagerOuterClass.TodoListManager parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hankstodo.app.TodoListManagerOuterClass.TodoListManager prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code hankstodo_app.TodoListManager}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          hankstodo.app.TodoListManagerOuterClass.TodoListManager, Builder> implements
        // @@protoc_insertion_point(builder_implements:hankstodo_app.TodoListManager)
        hankstodo.app.TodoListManagerOuterClass.TodoListManagerOrBuilder {
      // Construct using hankstodo.app.TodoListManagerOuterClass.TodoListManager.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string sid = 1;</code>
       */
      public java.lang.String getSid() {
        return instance.getSid();
      }
      /**
       * <code>optional string sid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSidBytes() {
        return instance.getSidBytes();
      }
      /**
       * <code>optional string sid = 1;</code>
       */
      public Builder setSid(
          java.lang.String value) {
        copyOnWrite();
        instance.setSid(value);
        return this;
      }
      /**
       * <code>optional string sid = 1;</code>
       */
      public Builder clearSid() {
        copyOnWrite();
        instance.clearSid();
        return this;
      }
      /**
       * <code>optional string sid = 1;</code>
       */
      public Builder setSidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSidBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hankstodo_app.TodoListManager)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new hankstodo.app.TodoListManagerOuterClass.TodoListManager();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          hankstodo.app.TodoListManagerOuterClass.TodoListManager other = (hankstodo.app.TodoListManagerOuterClass.TodoListManager) arg1;
          sid_ = visitor.visitString(!sid_.isEmpty(), sid_,
              !other.sid_.isEmpty(), other.sid_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  sid_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (hankstodo.app.TodoListManagerOuterClass.TodoListManager.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:hankstodo_app.TodoListManager)
    private static final hankstodo.app.TodoListManagerOuterClass.TodoListManager DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TodoListManager();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static hankstodo.app.TodoListManagerOuterClass.TodoListManager getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<TodoListManager> PARSER;

    public static com.google.protobuf.Parser<TodoListManager> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface newTodoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hankstodo_app.newTodo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string arg0 = 1;</code>
     */
    java.lang.String getArg0();
    /**
     * <code>optional string arg0 = 1;</code>
     */
    com.google.protobuf.ByteString
        getArg0Bytes();
  }
  /**
   * Protobuf type {@code hankstodo_app.newTodo}
   */
  public  static final class newTodo extends
      com.google.protobuf.GeneratedMessageLite<
          newTodo, newTodo.Builder> implements
      // @@protoc_insertion_point(message_implements:hankstodo_app.newTodo)
      newTodoOrBuilder {
    private newTodo() {
      arg0_ = "";
    }
    public static final int ARG0_FIELD_NUMBER = 1;
    private java.lang.String arg0_;
    /**
     * <code>optional string arg0 = 1;</code>
     */
    public java.lang.String getArg0() {
      return arg0_;
    }
    /**
     * <code>optional string arg0 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getArg0Bytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(arg0_);
    }
    /**
     * <code>optional string arg0 = 1;</code>
     */
    private void setArg0(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      arg0_ = value;
    }
    /**
     * <code>optional string arg0 = 1;</code>
     */
    private void clearArg0() {
      
      arg0_ = getDefaultInstance().getArg0();
    }
    /**
     * <code>optional string arg0 = 1;</code>
     */
    private void setArg0Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      arg0_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!arg0_.isEmpty()) {
        output.writeString(1, getArg0());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!arg0_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getArg0());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static hankstodo.app.TodoListManagerOuterClass.newTodo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static hankstodo.app.TodoListManagerOuterClass.newTodo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static hankstodo.app.TodoListManagerOuterClass.newTodo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static hankstodo.app.TodoListManagerOuterClass.newTodo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static hankstodo.app.TodoListManagerOuterClass.newTodo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListManagerOuterClass.newTodo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static hankstodo.app.TodoListManagerOuterClass.newTodo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListManagerOuterClass.newTodo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static hankstodo.app.TodoListManagerOuterClass.newTodo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListManagerOuterClass.newTodo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hankstodo.app.TodoListManagerOuterClass.newTodo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code hankstodo_app.newTodo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          hankstodo.app.TodoListManagerOuterClass.newTodo, Builder> implements
        // @@protoc_insertion_point(builder_implements:hankstodo_app.newTodo)
        hankstodo.app.TodoListManagerOuterClass.newTodoOrBuilder {
      // Construct using hankstodo.app.TodoListManagerOuterClass.newTodo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string arg0 = 1;</code>
       */
      public java.lang.String getArg0() {
        return instance.getArg0();
      }
      /**
       * <code>optional string arg0 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getArg0Bytes() {
        return instance.getArg0Bytes();
      }
      /**
       * <code>optional string arg0 = 1;</code>
       */
      public Builder setArg0(
          java.lang.String value) {
        copyOnWrite();
        instance.setArg0(value);
        return this;
      }
      /**
       * <code>optional string arg0 = 1;</code>
       */
      public Builder clearArg0() {
        copyOnWrite();
        instance.clearArg0();
        return this;
      }
      /**
       * <code>optional string arg0 = 1;</code>
       */
      public Builder setArg0Bytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setArg0Bytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hankstodo_app.newTodo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new hankstodo.app.TodoListManagerOuterClass.newTodo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          hankstodo.app.TodoListManagerOuterClass.newTodo other = (hankstodo.app.TodoListManagerOuterClass.newTodo) arg1;
          arg0_ = visitor.visitString(!arg0_.isEmpty(), arg0_,
              !other.arg0_.isEmpty(), other.arg0_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  arg0_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (hankstodo.app.TodoListManagerOuterClass.newTodo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:hankstodo_app.newTodo)
    private static final hankstodo.app.TodoListManagerOuterClass.newTodo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new newTodo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static hankstodo.app.TodoListManagerOuterClass.newTodo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<newTodo> PARSER;

    public static com.google.protobuf.Parser<newTodo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
