// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the required parameters.
type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4ca1392b6e13ff43, []int{0}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the required parameters.
type CreateReply struct {
	ObjId                string   `protobuf:"bytes,1,opt,name=ObjId" json:"ObjId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReply) Reset()         { *m = CreateReply{} }
func (m *CreateReply) String() string { return proto.CompactTextString(m) }
func (*CreateReply) ProtoMessage()    {}
func (*CreateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4ca1392b6e13ff43, []int{1}
}
func (m *CreateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReply.Unmarshal(m, b)
}
func (m *CreateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReply.Marshal(b, m, deterministic)
}
func (dst *CreateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReply.Merge(dst, src)
}
func (m *CreateReply) XXX_Size() int {
	return xxx_messageInfo_CreateReply.Size(m)
}
func (m *CreateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReply proto.InternalMessageInfo

func (m *CreateReply) GetObjId() string {
	if m != nil {
		return m.ObjId
	}
	return ""
}

// The request message containing the required parameters.
type DeleteRequest struct {
	ObjId                string   `protobuf:"bytes,1,opt,name=ObjId" json:"ObjId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4ca1392b6e13ff43, []int{2}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetObjId() string {
	if m != nil {
		return m.ObjId
	}
	return ""
}

// The response message containing the required parameters.
type DeleteReply struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReply) Reset()         { *m = DeleteReply{} }
func (m *DeleteReply) String() string { return proto.CompactTextString(m) }
func (*DeleteReply) ProtoMessage()    {}
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4ca1392b6e13ff43, []int{3}
}
func (m *DeleteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReply.Unmarshal(m, b)
}
func (m *DeleteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReply.Marshal(b, m, deterministic)
}
func (dst *DeleteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReply.Merge(dst, src)
}
func (m *DeleteReply) XXX_Size() int {
	return xxx_messageInfo_DeleteReply.Size(m)
}
func (m *DeleteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReply proto.InternalMessageInfo

func (m *DeleteReply) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

// The request message containing the required parameters.
type GenericMethodRequest struct {
	ObjId           string `protobuf:"bytes,1,opt,name=ObjId" json:"ObjId,omitempty"`
	SapphireObjName string `protobuf:"bytes,2,opt,name=sapphireObjName" json:"sapphireObjName,omitempty"`
	FuncName        string `protobuf:"bytes,3,opt,name=funcName" json:"funcName,omitempty"`
	Params          []byte `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	// repeated string paramNames=5;
	DmsList              []string `protobuf:"bytes,6,rep,name=dmsList" json:"dmsList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericMethodRequest) Reset()         { *m = GenericMethodRequest{} }
func (m *GenericMethodRequest) String() string { return proto.CompactTextString(m) }
func (*GenericMethodRequest) ProtoMessage()    {}
func (*GenericMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4ca1392b6e13ff43, []int{4}
}
func (m *GenericMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericMethodRequest.Unmarshal(m, b)
}
func (m *GenericMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericMethodRequest.Marshal(b, m, deterministic)
}
func (dst *GenericMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericMethodRequest.Merge(dst, src)
}
func (m *GenericMethodRequest) XXX_Size() int {
	return xxx_messageInfo_GenericMethodRequest.Size(m)
}
func (m *GenericMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenericMethodRequest proto.InternalMessageInfo

func (m *GenericMethodRequest) GetObjId() string {
	if m != nil {
		return m.ObjId
	}
	return ""
}

func (m *GenericMethodRequest) GetSapphireObjName() string {
	if m != nil {
		return m.SapphireObjName
	}
	return ""
}

func (m *GenericMethodRequest) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func (m *GenericMethodRequest) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *GenericMethodRequest) GetDmsList() []string {
	if m != nil {
		return m.DmsList
	}
	return nil
}

// The response message containing the required parameters.
type GenericMethodReply struct {
	Ret                  []byte   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericMethodReply) Reset()         { *m = GenericMethodReply{} }
func (m *GenericMethodReply) String() string { return proto.CompactTextString(m) }
func (*GenericMethodReply) ProtoMessage()    {}
func (*GenericMethodReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4ca1392b6e13ff43, []int{5}
}
func (m *GenericMethodReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericMethodReply.Unmarshal(m, b)
}
func (m *GenericMethodReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericMethodReply.Marshal(b, m, deterministic)
}
func (dst *GenericMethodReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericMethodReply.Merge(dst, src)
}
func (m *GenericMethodReply) XXX_Size() int {
	return xxx_messageInfo_GenericMethodReply.Size(m)
}
func (m *GenericMethodReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericMethodReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenericMethodReply proto.InternalMessageInfo

func (m *GenericMethodReply) GetRet() []byte {
	if m != nil {
		return m.Ret
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "api.CreateRequest")
	proto.RegisterType((*CreateReply)(nil), "api.CreateReply")
	proto.RegisterType((*DeleteRequest)(nil), "api.DeleteRequest")
	proto.RegisterType((*DeleteReply)(nil), "api.DeleteReply")
	proto.RegisterType((*GenericMethodRequest)(nil), "api.GenericMethodRequest")
	proto.RegisterType((*GenericMethodReply)(nil), "api.GenericMethodReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MgmtgrpcServiceClient is the client API for MgmtgrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MgmtgrpcServiceClient interface {
	CreateSapphireObject(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error)
	DeleteSapphireObject(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error)
	GenericMethodInvoke(ctx context.Context, in *GenericMethodRequest, opts ...grpc.CallOption) (*GenericMethodReply, error)
}

type mgmtgrpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewMgmtgrpcServiceClient(cc *grpc.ClientConn) MgmtgrpcServiceClient {
	return &mgmtgrpcServiceClient{cc}
}

func (c *mgmtgrpcServiceClient) CreateSapphireObject(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := c.cc.Invoke(ctx, "/api.MgmtgrpcService/CreateSapphireObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtgrpcServiceClient) DeleteSapphireObject(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error) {
	out := new(DeleteReply)
	err := c.cc.Invoke(ctx, "/api.MgmtgrpcService/DeleteSapphireObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtgrpcServiceClient) GenericMethodInvoke(ctx context.Context, in *GenericMethodRequest, opts ...grpc.CallOption) (*GenericMethodReply, error) {
	out := new(GenericMethodReply)
	err := c.cc.Invoke(ctx, "/api.MgmtgrpcService/GenericMethodInvoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MgmtgrpcService service

type MgmtgrpcServiceServer interface {
	CreateSapphireObject(context.Context, *CreateRequest) (*CreateReply, error)
	DeleteSapphireObject(context.Context, *DeleteRequest) (*DeleteReply, error)
	GenericMethodInvoke(context.Context, *GenericMethodRequest) (*GenericMethodReply, error)
}

func RegisterMgmtgrpcServiceServer(s *grpc.Server, srv MgmtgrpcServiceServer) {
	s.RegisterService(&_MgmtgrpcService_serviceDesc, srv)
}

func _MgmtgrpcService_CreateSapphireObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtgrpcServiceServer).CreateSapphireObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MgmtgrpcService/CreateSapphireObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtgrpcServiceServer).CreateSapphireObject(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtgrpcService_DeleteSapphireObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtgrpcServiceServer).DeleteSapphireObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MgmtgrpcService/DeleteSapphireObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtgrpcServiceServer).DeleteSapphireObject(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtgrpcService_GenericMethodInvoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtgrpcServiceServer).GenericMethodInvoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MgmtgrpcService/GenericMethodInvoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtgrpcServiceServer).GenericMethodInvoke(ctx, req.(*GenericMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MgmtgrpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MgmtgrpcService",
	HandlerType: (*MgmtgrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSapphireObject",
			Handler:    _MgmtgrpcService_CreateSapphireObject_Handler,
		},
		{
			MethodName: "DeleteSapphireObject",
			Handler:    _MgmtgrpcService_DeleteSapphireObject_Handler,
		},
		{
			MethodName: "GenericMethodInvoke",
			Handler:    _MgmtgrpcService_GenericMethodInvoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_4ca1392b6e13ff43) }

var fileDescriptor_api_4ca1392b6e13ff43 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xdf, 0x4e, 0xf2, 0x40,
	0x10, 0xc5, 0xe9, 0x57, 0x3e, 0x84, 0x01, 0x02, 0x19, 0x89, 0x56, 0xae, 0x70, 0x89, 0xa6, 0x57,
	0x5c, 0xe8, 0xbd, 0x37, 0x9a, 0x18, 0xa2, 0x48, 0x52, 0x9e, 0x60, 0x29, 0x03, 0x2c, 0xf6, 0xcf,
	0xba, 0x5d, 0x48, 0x78, 0x1f, 0x9f, 0xcb, 0x67, 0x31, 0xbb, 0x80, 0x58, 0xd2, 0x78, 0x37, 0xb3,
	0xf3, 0x9b, 0x93, 0xd3, 0x33, 0x85, 0x1a, 0x97, 0x62, 0x20, 0x55, 0xaa, 0x53, 0x74, 0xb9, 0x14,
	0xac, 0x0f, 0xcd, 0x47, 0x45, 0x5c, 0x53, 0x40, 0x1f, 0x6b, 0xca, 0x34, 0x22, 0x94, 0x13, 0x1e,
	0x93, 0xe7, 0xf4, 0x1c, 0xbf, 0x16, 0xd8, 0x9a, 0xf5, 0xa1, 0x7e, 0x80, 0x64, 0xb4, 0xc5, 0x0e,
	0xfc, 0x1f, 0x4f, 0x57, 0xc3, 0xd9, 0x9e, 0xd9, 0x35, 0xec, 0x06, 0x9a, 0x4f, 0x14, 0xd1, 0x51,
	0xa9, 0x18, 0xbb, 0x86, 0xfa, 0x01, 0x33, 0x5a, 0x08, 0xe5, 0x79, 0xc4, 0x17, 0x96, 0xa9, 0x06,
	0xb6, 0x66, 0x9f, 0x0e, 0x74, 0x9e, 0x29, 0x21, 0x25, 0xc2, 0x11, 0xe9, 0x65, 0x3a, 0xfb, 0x53,
	0x11, 0x7d, 0x68, 0x65, 0x5c, 0xca, 0xa5, 0x50, 0x34, 0x9e, 0xae, 0xde, 0x8c, 0xf9, 0x7f, 0x76,
	0x7e, 0xfa, 0x8c, 0x5d, 0xa8, 0xce, 0xd7, 0x49, 0x68, 0x11, 0xd7, 0x22, 0x3f, 0x3d, 0x5e, 0x40,
	0x45, 0x72, 0xc5, 0xe3, 0xcc, 0x2b, 0xf7, 0x1c, 0xbf, 0x11, 0xec, 0x3b, 0xf4, 0xe0, 0x6c, 0x16,
	0x67, 0xaf, 0x22, 0xd3, 0x5e, 0xa5, 0xe7, 0xfa, 0xb5, 0xe0, 0xd0, 0xb2, 0x5b, 0xc0, 0x13, 0x97,
	0xe6, 0x83, 0xda, 0xe0, 0x2a, 0xd2, 0xd6, 0x61, 0x23, 0x30, 0xe5, 0xdd, 0x97, 0x03, 0xad, 0xd1,
	0x22, 0xd6, 0x0b, 0x25, 0xc3, 0x09, 0xa9, 0x8d, 0x08, 0x09, 0x1f, 0xa0, 0xb3, 0x4b, 0x74, 0x72,
	0xb4, 0x48, 0xa1, 0x46, 0x1c, 0x98, 0xfb, 0xe4, 0x2e, 0xd2, 0x6d, 0xe7, 0xde, 0x64, 0xb4, 0x65,
	0x25, 0xb3, 0xbf, 0x4b, 0xb1, 0x70, 0x3f, 0x77, 0x87, 0xfd, 0xfe, 0xaf, 0xd0, 0x59, 0x09, 0x5f,
	0xe0, 0x3c, 0xe7, 0x7d, 0x98, 0x6c, 0xd2, 0x77, 0xc2, 0x2b, 0x8b, 0x16, 0x65, 0xdf, 0xbd, 0x2c,
	0x1a, 0x59, 0xb1, 0x69, 0xc5, 0xfe, 0x4f, 0xf7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x4d,
	0x50, 0x3a, 0x5c, 0x02, 0x00, 0x00,
}
