// Code generated by protoc-gen-go. DO NOT EDIT.
// source: so.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the required parameters.
type HelloWorldRequest struct {
	Num                  int32    `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldRequest) Reset()         { *m = HelloWorldRequest{} }
func (m *HelloWorldRequest) String() string { return proto.CompactTextString(m) }
func (*HelloWorldRequest) ProtoMessage()    {}
func (*HelloWorldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_so_e00249ac60aa2a18, []int{0}
}
func (m *HelloWorldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldRequest.Unmarshal(m, b)
}
func (m *HelloWorldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldRequest.Marshal(b, m, deterministic)
}
func (dst *HelloWorldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldRequest.Merge(dst, src)
}
func (m *HelloWorldRequest) XXX_Size() int {
	return xxx_messageInfo_HelloWorldRequest.Size(m)
}
func (m *HelloWorldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldRequest proto.InternalMessageInfo

func (m *HelloWorldRequest) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *HelloWorldRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the required parameters.
type HelloWorldReply struct {
	RetName              string   `protobuf:"bytes,1,opt,name=retName" json:"retName,omitempty"`
	Retval               int32    `protobuf:"varint,2,opt,name=retval" json:"retval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldReply) Reset()         { *m = HelloWorldReply{} }
func (m *HelloWorldReply) String() string { return proto.CompactTextString(m) }
func (*HelloWorldReply) ProtoMessage()    {}
func (*HelloWorldReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_so_e00249ac60aa2a18, []int{1}
}
func (m *HelloWorldReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldReply.Unmarshal(m, b)
}
func (m *HelloWorldReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldReply.Marshal(b, m, deterministic)
}
func (dst *HelloWorldReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldReply.Merge(dst, src)
}
func (m *HelloWorldReply) XXX_Size() int {
	return xxx_messageInfo_HelloWorldReply.Size(m)
}
func (m *HelloWorldReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldReply proto.InternalMessageInfo

func (m *HelloWorldReply) GetRetName() string {
	if m != nil {
		return m.RetName
	}
	return ""
}

func (m *HelloWorldReply) GetRetval() int32 {
	if m != nil {
		return m.Retval
	}
	return 0
}

// The request message containing the required parameters.
type FibbonaciRequest struct {
	Num                  int32    `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FibbonaciRequest) Reset()         { *m = FibbonaciRequest{} }
func (m *FibbonaciRequest) String() string { return proto.CompactTextString(m) }
func (*FibbonaciRequest) ProtoMessage()    {}
func (*FibbonaciRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_so_e00249ac60aa2a18, []int{2}
}
func (m *FibbonaciRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FibbonaciRequest.Unmarshal(m, b)
}
func (m *FibbonaciRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FibbonaciRequest.Marshal(b, m, deterministic)
}
func (dst *FibbonaciRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibbonaciRequest.Merge(dst, src)
}
func (m *FibbonaciRequest) XXX_Size() int {
	return xxx_messageInfo_FibbonaciRequest.Size(m)
}
func (m *FibbonaciRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FibbonaciRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FibbonaciRequest proto.InternalMessageInfo

func (m *FibbonaciRequest) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

// The response message containing the required parameters.
type FibbonaciReply struct {
	Ret                  string   `protobuf:"bytes,1,opt,name=ret" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FibbonaciReply) Reset()         { *m = FibbonaciReply{} }
func (m *FibbonaciReply) String() string { return proto.CompactTextString(m) }
func (*FibbonaciReply) ProtoMessage()    {}
func (*FibbonaciReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_so_e00249ac60aa2a18, []int{3}
}
func (m *FibbonaciReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FibbonaciReply.Unmarshal(m, b)
}
func (m *FibbonaciReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FibbonaciReply.Marshal(b, m, deterministic)
}
func (dst *FibbonaciReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibbonaciReply.Merge(dst, src)
}
func (m *FibbonaciReply) XXX_Size() int {
	return xxx_messageInfo_FibbonaciReply.Size(m)
}
func (m *FibbonaciReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FibbonaciReply.DiscardUnknown(m)
}

var xxx_messageInfo_FibbonaciReply proto.InternalMessageInfo

func (m *FibbonaciReply) GetRet() string {
	if m != nil {
		return m.Ret
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloWorldRequest)(nil), "api.HelloWorldRequest")
	proto.RegisterType((*HelloWorldReply)(nil), "api.HelloWorldReply")
	proto.RegisterType((*FibbonaciRequest)(nil), "api.FibbonaciRequest")
	proto.RegisterType((*FibbonaciReply)(nil), "api.FibbonaciReply")
}

func init() { proto.RegisterFile("so.proto", fileDescriptor_so_e00249ac60aa2a18) }

var fileDescriptor_so_e00249ac60aa2a18 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0xce, 0xd7, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xb2, 0xe4, 0x12, 0xf4, 0x48, 0xcd,
	0xc9, 0xc9, 0x0f, 0xcf, 0x2f, 0xca, 0x49, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12,
	0xe0, 0x62, 0xce, 0x2b, 0xcd, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0x31, 0x85, 0x84,
	0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25,
	0x67, 0x2e, 0x7e, 0x64, 0xad, 0x05, 0x39, 0x95, 0x42, 0x12, 0x5c, 0xec, 0x45, 0xa9, 0x25, 0x7e,
	0x20, 0x95, 0x8c, 0x60, 0x95, 0x30, 0xae, 0x90, 0x18, 0x17, 0x5b, 0x51, 0x6a, 0x49, 0x59, 0x62,
	0x0e, 0xd8, 0x08, 0xd6, 0x20, 0x28, 0x4f, 0x49, 0x85, 0x4b, 0xc0, 0x2d, 0x33, 0x29, 0x29, 0x3f,
	0x2f, 0x31, 0x39, 0x13, 0xa7, 0xf5, 0x4a, 0x4a, 0x5c, 0x7c, 0x48, 0xaa, 0x40, 0x36, 0x09, 0x70,
	0x31, 0x17, 0xa5, 0x96, 0x40, 0x6d, 0x01, 0x31, 0x93, 0xd8, 0xc0, 0xbe, 0x32, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x9c, 0x3c, 0x0c, 0xf7, 0xe1, 0x00, 0x00, 0x00,
}
