/*
 * Stub for class sapphire.demo.KVStore
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.demo.stubs;

public final class KVStore_Stub extends sapphire.demo.KVStore
        implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public KVStore_Stub() {
        super();
    }

    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }

    // Implementation of vote(UUID)
    public sapphire.policy.transaction.TransactionManager.Vote vote(java.util.UUID $param_UUID_1)
            throws sapphire.policy.transaction.TransactionExecutionException {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                $__result = super.vote($param_UUID_1);
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method =
                    "public sapphire.policy.transaction.TransactionManager$Vote sapphire.demo.KVStore.vote(java.util.UUID) throws sapphire.policy.transaction.TransactionExecutionException";
            $__params.add($param_UUID_1);
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof sapphire.policy.transaction.TransactionExecutionException) {
                    throw (sapphire.policy.transaction.TransactionExecutionException) ex;
                } else if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (sapphire.policy.transaction.TransactionExecutionException e) {
                throw e;
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
        return ((sapphire.policy.transaction.TransactionManager.Vote) $__result);
    }

    // Implementation of startTransaction(long)
    public void startTransaction(long $param_long_1)
            throws sapphire.policy.serializability.TransactionAlreadyStartedException,
                    sapphire.policy.serializability.TransactionException {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                super.startTransaction($param_long_1);
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method =
                    "public void sapphire.demo.KVStore.startTransaction(long) throws sapphire.policy.serializability.TransactionAlreadyStartedException,sapphire.policy.serializability.TransactionException";
            $__params.add($param_long_1);
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex
                        instanceof
                        sapphire.policy.serializability.TransactionAlreadyStartedException) {
                    throw (sapphire.policy.serializability.TransactionAlreadyStartedException) ex;
                } else if (ex instanceof sapphire.policy.serializability.TransactionException) {
                    throw (sapphire.policy.serializability.TransactionException) ex;
                } else if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (sapphire.policy.serializability.TransactionAlreadyStartedException e) {
                throw e;
            } catch (sapphire.policy.serializability.TransactionException e) {
                throw e;
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
    }

    // Implementation of startTransaction()
    public void startTransaction()
            throws sapphire.policy.serializability.TransactionAlreadyStartedException,
                    sapphire.policy.serializability.TransactionException {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                super.startTransaction();
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method =
                    "public void sapphire.demo.KVStore.startTransaction() throws sapphire.policy.serializability.TransactionAlreadyStartedException,sapphire.policy.serializability.TransactionException";
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex
                        instanceof
                        sapphire.policy.serializability.TransactionAlreadyStartedException) {
                    throw (sapphire.policy.serializability.TransactionAlreadyStartedException) ex;
                } else if (ex instanceof sapphire.policy.serializability.TransactionException) {
                    throw (sapphire.policy.serializability.TransactionException) ex;
                } else if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (sapphire.policy.serializability.TransactionAlreadyStartedException e) {
                throw e;
            } catch (sapphire.policy.serializability.TransactionException e) {
                throw e;
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
    }

    // Implementation of set(String, Serializable)
    public void set(java.lang.String $param_String_1, java.io.Serializable $param_Serializable_2) {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                super.set($param_String_1, $param_Serializable_2);
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method =
                    "public void sapphire.demo.KVStore.set(java.lang.String,java.io.Serializable)";
            $__params.add($param_String_1);
            $__params.add($param_Serializable_2);
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
    }

    // Implementation of saveCheckpoint()
    public void saveCheckpoint() throws java.lang.Exception {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                super.saveCheckpoint();
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method =
                    "public void sapphire.demo.KVStore.saveCheckpoint() throws java.lang.Exception";
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
    }

    // Implementation of rollbackTransaction()
    public void rollbackTransaction()
            throws sapphire.policy.serializability.NoTransactionStartedException,
                    sapphire.policy.serializability.TransactionException {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                super.rollbackTransaction();
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method =
                    "public void sapphire.demo.KVStore.rollbackTransaction() throws sapphire.policy.serializability.NoTransactionStartedException,sapphire.policy.serializability.TransactionException";
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof sapphire.policy.serializability.NoTransactionStartedException) {
                    throw (sapphire.policy.serializability.NoTransactionStartedException) ex;
                } else if (ex instanceof sapphire.policy.serializability.TransactionException) {
                    throw (sapphire.policy.serializability.TransactionException) ex;
                } else if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (sapphire.policy.serializability.NoTransactionStartedException e) {
                throw e;
            } catch (sapphire.policy.serializability.TransactionException e) {
                throw e;
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
    }

    // Implementation of restoreCheckpoint()
    public void restoreCheckpoint() throws java.lang.Exception {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                super.restoreCheckpoint();
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method =
                    "public void sapphire.demo.KVStore.restoreCheckpoint() throws java.lang.Exception";
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
    }

    // Implementation of remove(String)
    public java.io.Serializable remove(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                $__result = super.remove($param_String_1);
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method =
                    "public java.io.Serializable sapphire.demo.KVStore.remove(java.lang.String)";
            $__params.add($param_String_1);
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
        return ((java.io.Serializable) $__result);
    }

    // Implementation of push()
    public void push() {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                super.push();
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method = "public void sapphire.demo.KVStore.push()";
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
    }

    // Implementation of pull()
    public void pull() {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                super.pull();
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method = "public void sapphire.demo.KVStore.pull()";
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
    }

    // Implementation of migrateObject(InetSocketAddress)
    public void migrateObject(java.net.InetSocketAddress $param_InetSocketAddress_1)
            throws sapphire.policy.mobility.explicitmigration.MigrationException {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                super.migrateObject($param_InetSocketAddress_1);
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method =
                    "public void sapphire.demo.KVStore.migrateObject(java.net.InetSocketAddress) throws sapphire.policy.mobility.explicitmigration.MigrationException";
            $__params.add($param_InetSocketAddress_1);
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof sapphire.policy.mobility.explicitmigration.MigrationException) {
                    throw (sapphire.policy.mobility.explicitmigration.MigrationException) ex;
                } else if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (sapphire.policy.mobility.explicitmigration.MigrationException e) {
                throw e;
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
    }

    // Implementation of leave(UUID)
    public void leave(java.util.UUID $param_UUID_1) {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                super.leave($param_UUID_1);
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method = "public void sapphire.demo.KVStore.leave(java.util.UUID)";
            $__params.add($param_UUID_1);
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
    }

    // Implementation of join(UUID)
    public void join(java.util.UUID $param_UUID_1)
            throws sapphire.policy.serializability.TransactionAlreadyStartedException {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                super.join($param_UUID_1);
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method =
                    "public void sapphire.demo.KVStore.join(java.util.UUID) throws sapphire.policy.serializability.TransactionAlreadyStartedException";
            $__params.add($param_UUID_1);
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex
                        instanceof
                        sapphire.policy.serializability.TransactionAlreadyStartedException) {
                    throw (sapphire.policy.serializability.TransactionAlreadyStartedException) ex;
                } else if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (sapphire.policy.serializability.TransactionAlreadyStartedException e) {
                throw e;
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
    }

    // Implementation of get(String)
    public java.io.Serializable get(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                $__result = super.get($param_String_1);
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method =
                    "public java.io.Serializable sapphire.demo.KVStore.get(java.lang.String)";
            $__params.add($param_String_1);
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
        return ((java.io.Serializable) $__result);
    }

    // Implementation of commitTransaction()
    public void commitTransaction()
            throws sapphire.policy.serializability.NoTransactionStartedException,
                    sapphire.policy.serializability.TransactionException {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                super.commitTransaction();
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method =
                    "public void sapphire.demo.KVStore.commitTransaction() throws sapphire.policy.serializability.NoTransactionStartedException,sapphire.policy.serializability.TransactionException";
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof sapphire.policy.serializability.NoTransactionStartedException) {
                    throw (sapphire.policy.serializability.NoTransactionStartedException) ex;
                } else if (ex instanceof sapphire.policy.serializability.TransactionException) {
                    throw (sapphire.policy.serializability.TransactionException) ex;
                } else if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (sapphire.policy.serializability.NoTransactionStartedException e) {
                throw e;
            } catch (sapphire.policy.serializability.TransactionException e) {
                throw e;
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
    }

    // Implementation of commit(UUID)
    public void commit(java.util.UUID $param_UUID_1) {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                super.commit($param_UUID_1);
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method = "public void sapphire.demo.KVStore.commit(java.util.UUID)";
            $__params.add($param_UUID_1);
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
    }

    // Implementation of abort(UUID)
    public void abort(java.util.UUID $param_UUID_1) {
        java.lang.Object $__result = null;
        if ($__directInvocation) {
            try {
                super.abort($param_UUID_1);
            } catch (java.lang.Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method = "public void sapphire.demo.KVStore.abort(java.util.UUID)";
            $__params.add($param_UUID_1);
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof java.lang.RuntimeException) {
                    throw (java.lang.RuntimeException) ex;
                } else {
                    throw new java.lang.RuntimeException(ex);
                }
            } catch (java.lang.RuntimeException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new java.lang.RuntimeException(e);
            }
        }
    }
}
