FROM alpine:3.7

MAINTAINER Vinay Kulkarni <vinay.kulkarni@huawei.com>

RUN apk --update add openjdk8-jre bind-tools

COPY [ "jars/*", "/dcap/jars/" ]
COPY [ "client.policy", \
       "common.inc", \
       "start-oms.sh", \
       "start-kernelserver.sh", \
       "start-app.sh", \
       "/dcap/" ]

ENTRYPOINT tail -f /dev/null
