/*
 * Stub for class sapphire.policy.dht.DHTPolicy.DHTServerPolicy
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.policy.stubs;


public final class DHTPolicy$DHTServerPolicy_Stub extends sapphire.policy.dht.DHTPolicy.DHTServerPolicy implements sapphire.kernel.common.KernelObjectStub {

    sapphire.kernel.common.KernelOID $__oid = null;
    java.net.InetSocketAddress $__hostname = null;

    public DHTPolicy$DHTServerPolicy_Stub(sapphire.kernel.common.KernelOID oid) {
        this.$__oid = oid;
    }

    public sapphire.kernel.common.KernelOID $__getKernelOID() {
        return this.$__oid;
    }

    public java.net.InetSocketAddress $__getHostname() {
        return this.$__hostname;
    }

    public void $__updateHostname(java.net.InetSocketAddress hostname) {
        this.$__hostname = hostname;
    }

    public Object $__makeKernelRPC(java.lang.String method, java.util.ArrayList<Object> params) throws java.rmi.RemoteException, java.lang.Exception {
        sapphire.kernel.common.KernelRPC rpc = new sapphire.kernel.common.KernelRPC($__oid, method, params);
        try {
            return sapphire.kernel.common.GlobalKernelReferences.nodeServer.getKernelClient().makeKernelRPC(this, rpc);
        } catch (sapphire.kernel.common.KernelObjectNotFoundException e) {
            throw new java.rmi.RemoteException();
        }
    }

    @Override
    public boolean equals(Object obj) { 
        DHTPolicy$DHTServerPolicy_Stub other = (DHTPolicy$DHTServerPolicy_Stub) obj;
        if (! other.$__oid.equals($__oid))
            return false;
        return true;
    }
    @Override
    public int hashCode() { 
        return $__oid.getID();
    }


    // Implementation of setKey(DHTKey)
    public void setKey(sapphire.policy.interfaces.dht.DHTKey $param_DHTKey_1) {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.dht.DHTPolicy$DHTServerPolicy.setKey(sapphire.policy.interfaces.dht.DHTKey)";
        $__params.add($param_DHTKey_1);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of onRPC(String, ArrayList)
    public java.lang.Object onRPC(java.lang.String $param_String_1, java.util.ArrayList $param_ArrayList_2)
            throws java.lang.Exception {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public java.lang.Object sapphire.policy.dht.DHTPolicy$DHTServerPolicy.onRPC(java.lang.String,java.util.ArrayList<java.lang.Object>) throws java.lang.Exception";
        $__params.add($param_String_1);
        $__params.add($param_ArrayList_2);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return $__result;
    }

    // Implementation of onMembershipChange()
    public void onMembershipChange() {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.dht.DHTPolicy$DHTServerPolicy.onMembershipChange()";
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of onCreate(SapphirePolicy.SapphireGroupPolicy)
    public void onCreate(sapphire.policy.SapphirePolicy.SapphireGroupPolicy $param_SapphirePolicy$SapphireGroupPolicy_1) {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.dht.DHTPolicy$DHTServerPolicy.onCreate(sapphire.policy.SapphirePolicy$SapphireGroupPolicy)";
        $__params.add($param_SapphirePolicy$SapphireGroupPolicy_1);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of getGroup()
    public sapphire.policy.SapphirePolicy.SapphireGroupPolicy getGroup() {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public sapphire.policy.SapphirePolicy$SapphireGroupPolicy sapphire.policy.dht.DHTPolicy$DHTServerPolicy.getGroup()";
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.policy.SapphirePolicy.SapphireGroupPolicy) $__result);
    }

    // Implementation of forwardedRPC(String, ArrayList)
    public java.lang.Object forwardedRPC(java.lang.String $param_String_1, java.util.ArrayList $param_ArrayList_2)
            throws java.lang.Exception {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public java.lang.Object sapphire.policy.dht.DHTPolicy$DHTServerPolicy.forwardedRPC(java.lang.String,java.util.ArrayList<java.lang.Object>) throws java.lang.Exception";
        $__params.add($param_String_1);
        $__params.add($param_ArrayList_2);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return $__result;
    }

    // Implementation of dhtReplicate()
    public sapphire.policy.dht.DHTPolicy.DHTServerPolicy dhtReplicate() {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public sapphire.policy.dht.DHTPolicy$DHTServerPolicy sapphire.policy.dht.DHTPolicy$DHTServerPolicy.dhtReplicate()";
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.policy.dht.DHTPolicy.DHTServerPolicy) $__result);
    }

    // Implementation of dhtPin(String)
    public void dhtPin(java.lang.String $param_String_1)
            throws java.rmi.RemoteException {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.dht.DHTPolicy$DHTServerPolicy.dhtPin(java.lang.String) throws java.rmi.RemoteException";
        $__params.add($param_String_1);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of dhtGetKeys(DHTPolicy.DHTServerPolicy, DHTKey)
    public void dhtGetKeys(sapphire.policy.dht.DHTPolicy.DHTServerPolicy $param_DHTPolicy$DHTServerPolicy_1, sapphire.policy.interfaces.dht.DHTKey $param_DHTKey_2) {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.dht.DHTPolicy$DHTServerPolicy.dhtGetKeys(sapphire.policy.dht.DHTPolicy$DHTServerPolicy,sapphire.policy.interfaces.dht.DHTKey)";
        $__params.add($param_DHTPolicy$DHTServerPolicy_1);
        $__params.add($param_DHTKey_2);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of dhtGetKeys(DHTKey)
    public java.util.Map dhtGetKeys(sapphire.policy.interfaces.dht.DHTKey $param_DHTKey_1) {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public java.util.Map<sapphire.policy.interfaces.dht.DHTKey, java.lang.Object> sapphire.policy.dht.DHTPolicy$DHTServerPolicy.dhtGetKeys(sapphire.policy.interfaces.dht.DHTKey)";
        $__params.add($param_DHTKey_1);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.Map) $__result);
    }

    // Implementation of dhtDelete(DHTKey)
    public void dhtDelete(sapphire.policy.interfaces.dht.DHTKey $param_DHTKey_1) {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.dht.DHTPolicy$DHTServerPolicy.dhtDelete(sapphire.policy.interfaces.dht.DHTKey)";
        $__params.add($param_DHTKey_1);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of dhtClear()
    public void dhtClear() {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.dht.DHTPolicy$DHTServerPolicy.dhtClear()";
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
