// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToApp.proto

package sapphire.kernel.app;

/**
 * Protobuf type {@code sapphire.kernel.app.CreateRequest}
 */
public  final class CreateRequest extends
    com.google.protobuf.GeneratedMessageLite<
        CreateRequest, CreateRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:sapphire.kernel.app.CreateRequest)
    CreateRequestOrBuilder {
  private CreateRequest() {
    soName_ = "";
    constructName_ = "";
    constructParams_ = com.google.protobuf.ByteString.EMPTY;
    langType_ = "";
  }
  public static final int SONAME_FIELD_NUMBER = 1;
  private java.lang.String soName_;
  /**
   * <code>optional string soName = 1;</code>
   */
  public java.lang.String getSoName() {
    return soName_;
  }
  /**
   * <code>optional string soName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSoNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(soName_);
  }
  /**
   * <code>optional string soName = 1;</code>
   */
  private void setSoName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    soName_ = value;
  }
  /**
   * <code>optional string soName = 1;</code>
   */
  private void clearSoName() {
    
    soName_ = getDefaultInstance().getSoName();
  }
  /**
   * <code>optional string soName = 1;</code>
   */
  private void setSoNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    soName_ = value.toStringUtf8();
  }

  public static final int CONSTRUCTNAME_FIELD_NUMBER = 2;
  private java.lang.String constructName_;
  /**
   * <code>optional string constructName = 2;</code>
   */
  public java.lang.String getConstructName() {
    return constructName_;
  }
  /**
   * <code>optional string constructName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getConstructNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(constructName_);
  }
  /**
   * <code>optional string constructName = 2;</code>
   */
  private void setConstructName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    constructName_ = value;
  }
  /**
   * <code>optional string constructName = 2;</code>
   */
  private void clearConstructName() {
    
    constructName_ = getDefaultInstance().getConstructName();
  }
  /**
   * <code>optional string constructName = 2;</code>
   */
  private void setConstructNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    constructName_ = value.toStringUtf8();
  }

  public static final int CONSTRUCTPARAMS_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString constructParams_;
  /**
   * <code>optional bytes constructParams = 3;</code>
   */
  public com.google.protobuf.ByteString getConstructParams() {
    return constructParams_;
  }
  /**
   * <code>optional bytes constructParams = 3;</code>
   */
  private void setConstructParams(com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    constructParams_ = value;
  }
  /**
   * <code>optional bytes constructParams = 3;</code>
   */
  private void clearConstructParams() {
    
    constructParams_ = getDefaultInstance().getConstructParams();
  }

  public static final int LANGTYPE_FIELD_NUMBER = 4;
  private java.lang.String langType_;
  /**
   * <code>optional string langType = 4;</code>
   */
  public java.lang.String getLangType() {
    return langType_;
  }
  /**
   * <code>optional string langType = 4;</code>
   */
  public com.google.protobuf.ByteString
      getLangTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(langType_);
  }
  /**
   * <code>optional string langType = 4;</code>
   */
  private void setLangType(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    langType_ = value;
  }
  /**
   * <code>optional string langType = 4;</code>
   */
  private void clearLangType() {
    
    langType_ = getDefaultInstance().getLangType();
  }
  /**
   * <code>optional string langType = 4;</code>
   */
  private void setLangTypeBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    langType_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!soName_.isEmpty()) {
      output.writeString(1, getSoName());
    }
    if (!constructName_.isEmpty()) {
      output.writeString(2, getConstructName());
    }
    if (!constructParams_.isEmpty()) {
      output.writeBytes(3, constructParams_);
    }
    if (!langType_.isEmpty()) {
      output.writeString(4, getLangType());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!soName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getSoName());
    }
    if (!constructName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getConstructName());
    }
    if (!constructParams_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, constructParams_);
    }
    if (!langType_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(4, getLangType());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static sapphire.kernel.app.CreateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.kernel.app.CreateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.kernel.app.CreateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.kernel.app.CreateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.kernel.app.CreateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.CreateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.kernel.app.CreateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.CreateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.kernel.app.CreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.CreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sapphire.kernel.app.CreateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code sapphire.kernel.app.CreateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        sapphire.kernel.app.CreateRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:sapphire.kernel.app.CreateRequest)
      sapphire.kernel.app.CreateRequestOrBuilder {
    // Construct using sapphire.kernel.app.CreateRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string soName = 1;</code>
     */
    public java.lang.String getSoName() {
      return instance.getSoName();
    }
    /**
     * <code>optional string soName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSoNameBytes() {
      return instance.getSoNameBytes();
    }
    /**
     * <code>optional string soName = 1;</code>
     */
    public Builder setSoName(
        java.lang.String value) {
      copyOnWrite();
      instance.setSoName(value);
      return this;
    }
    /**
     * <code>optional string soName = 1;</code>
     */
    public Builder clearSoName() {
      copyOnWrite();
      instance.clearSoName();
      return this;
    }
    /**
     * <code>optional string soName = 1;</code>
     */
    public Builder setSoNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSoNameBytes(value);
      return this;
    }

    /**
     * <code>optional string constructName = 2;</code>
     */
    public java.lang.String getConstructName() {
      return instance.getConstructName();
    }
    /**
     * <code>optional string constructName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getConstructNameBytes() {
      return instance.getConstructNameBytes();
    }
    /**
     * <code>optional string constructName = 2;</code>
     */
    public Builder setConstructName(
        java.lang.String value) {
      copyOnWrite();
      instance.setConstructName(value);
      return this;
    }
    /**
     * <code>optional string constructName = 2;</code>
     */
    public Builder clearConstructName() {
      copyOnWrite();
      instance.clearConstructName();
      return this;
    }
    /**
     * <code>optional string constructName = 2;</code>
     */
    public Builder setConstructNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setConstructNameBytes(value);
      return this;
    }

    /**
     * <code>optional bytes constructParams = 3;</code>
     */
    public com.google.protobuf.ByteString getConstructParams() {
      return instance.getConstructParams();
    }
    /**
     * <code>optional bytes constructParams = 3;</code>
     */
    public Builder setConstructParams(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setConstructParams(value);
      return this;
    }
    /**
     * <code>optional bytes constructParams = 3;</code>
     */
    public Builder clearConstructParams() {
      copyOnWrite();
      instance.clearConstructParams();
      return this;
    }

    /**
     * <code>optional string langType = 4;</code>
     */
    public java.lang.String getLangType() {
      return instance.getLangType();
    }
    /**
     * <code>optional string langType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLangTypeBytes() {
      return instance.getLangTypeBytes();
    }
    /**
     * <code>optional string langType = 4;</code>
     */
    public Builder setLangType(
        java.lang.String value) {
      copyOnWrite();
      instance.setLangType(value);
      return this;
    }
    /**
     * <code>optional string langType = 4;</code>
     */
    public Builder clearLangType() {
      copyOnWrite();
      instance.clearLangType();
      return this;
    }
    /**
     * <code>optional string langType = 4;</code>
     */
    public Builder setLangTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLangTypeBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sapphire.kernel.app.CreateRequest)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new sapphire.kernel.app.CreateRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        sapphire.kernel.app.CreateRequest other = (sapphire.kernel.app.CreateRequest) arg1;
        soName_ = visitor.visitString(!soName_.isEmpty(), soName_,
            !other.soName_.isEmpty(), other.soName_);
        constructName_ = visitor.visitString(!constructName_.isEmpty(), constructName_,
            !other.constructName_.isEmpty(), other.constructName_);
        constructParams_ = visitor.visitByteString(constructParams_ != com.google.protobuf.ByteString.EMPTY, constructParams_,
            other.constructParams_ != com.google.protobuf.ByteString.EMPTY, other.constructParams_);
        langType_ = visitor.visitString(!langType_.isEmpty(), langType_,
            !other.langType_.isEmpty(), other.langType_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                soName_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                constructName_ = s;
                break;
              }
              case 26: {

                constructParams_ = input.readBytes();
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                langType_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (sapphire.kernel.app.CreateRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sapphire.kernel.app.CreateRequest)
  private static final sapphire.kernel.app.CreateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CreateRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static sapphire.kernel.app.CreateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CreateRequest> PARSER;

  public static com.google.protobuf.Parser<CreateRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

