// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToApp.proto

package sapphire.kernel.app;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sapphire.kernel.app.CreateRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string soName = 1;</code>
   */
  java.lang.String getSoName();
  /**
   * <code>optional string soName = 1;</code>
   */
  com.google.protobuf.ByteString
      getSoNameBytes();

  /**
   * <code>optional string constructName = 2;</code>
   */
  java.lang.String getConstructName();
  /**
   * <code>optional string constructName = 2;</code>
   */
  com.google.protobuf.ByteString
      getConstructNameBytes();

  /**
   * <code>optional bytes constructParams = 3;</code>
   */
  com.google.protobuf.ByteString getConstructParams();

  /**
   * <code>optional string langType = 4;</code>
   */
  java.lang.String getLangType();
  /**
   * <code>optional string langType = 4;</code>
   */
  com.google.protobuf.ByteString
      getLangTypeBytes();
}
