// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToApp.proto

package sapphire.kernel.app;

/**
 * Protobuf type {@code sapphire.kernel.app.DetachRequest}
 */
public  final class DetachRequest extends
    com.google.protobuf.GeneratedMessageLite<
        DetachRequest, DetachRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:sapphire.kernel.app.DetachRequest)
    DetachRequestOrBuilder {
  private DetachRequest() {
    sId_ = "";
    clientId_ = "";
  }
  public static final int SID_FIELD_NUMBER = 1;
  private java.lang.String sId_;
  /**
   * <code>optional string sId = 1;</code>
   */
  public java.lang.String getSId() {
    return sId_;
  }
  /**
   * <code>optional string sId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sId_);
  }
  /**
   * <code>optional string sId = 1;</code>
   */
  private void setSId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    sId_ = value;
  }
  /**
   * <code>optional string sId = 1;</code>
   */
  private void clearSId() {
    
    sId_ = getDefaultInstance().getSId();
  }
  /**
   * <code>optional string sId = 1;</code>
   */
  private void setSIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    sId_ = value.toStringUtf8();
  }

  public static final int CLIENTID_FIELD_NUMBER = 2;
  private java.lang.String clientId_;
  /**
   * <code>optional string clientId = 2;</code>
   */
  public java.lang.String getClientId() {
    return clientId_;
  }
  /**
   * <code>optional string clientId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(clientId_);
  }
  /**
   * <code>optional string clientId = 2;</code>
   */
  private void setClientId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    clientId_ = value;
  }
  /**
   * <code>optional string clientId = 2;</code>
   */
  private void clearClientId() {
    
    clientId_ = getDefaultInstance().getClientId();
  }
  /**
   * <code>optional string clientId = 2;</code>
   */
  private void setClientIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    clientId_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!sId_.isEmpty()) {
      output.writeString(1, getSId());
    }
    if (!clientId_.isEmpty()) {
      output.writeString(2, getClientId());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!sId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getSId());
    }
    if (!clientId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getClientId());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static sapphire.kernel.app.DetachRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.kernel.app.DetachRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.kernel.app.DetachRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.kernel.app.DetachRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.kernel.app.DetachRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.DetachRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.kernel.app.DetachRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.DetachRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.kernel.app.DetachRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.DetachRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sapphire.kernel.app.DetachRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code sapphire.kernel.app.DetachRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        sapphire.kernel.app.DetachRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:sapphire.kernel.app.DetachRequest)
      sapphire.kernel.app.DetachRequestOrBuilder {
    // Construct using sapphire.kernel.app.DetachRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string sId = 1;</code>
     */
    public java.lang.String getSId() {
      return instance.getSId();
    }
    /**
     * <code>optional string sId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSIdBytes() {
      return instance.getSIdBytes();
    }
    /**
     * <code>optional string sId = 1;</code>
     */
    public Builder setSId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSId(value);
      return this;
    }
    /**
     * <code>optional string sId = 1;</code>
     */
    public Builder clearSId() {
      copyOnWrite();
      instance.clearSId();
      return this;
    }
    /**
     * <code>optional string sId = 1;</code>
     */
    public Builder setSIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSIdBytes(value);
      return this;
    }

    /**
     * <code>optional string clientId = 2;</code>
     */
    public java.lang.String getClientId() {
      return instance.getClientId();
    }
    /**
     * <code>optional string clientId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      return instance.getClientIdBytes();
    }
    /**
     * <code>optional string clientId = 2;</code>
     */
    public Builder setClientId(
        java.lang.String value) {
      copyOnWrite();
      instance.setClientId(value);
      return this;
    }
    /**
     * <code>optional string clientId = 2;</code>
     */
    public Builder clearClientId() {
      copyOnWrite();
      instance.clearClientId();
      return this;
    }
    /**
     * <code>optional string clientId = 2;</code>
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setClientIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sapphire.kernel.app.DetachRequest)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new sapphire.kernel.app.DetachRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        sapphire.kernel.app.DetachRequest other = (sapphire.kernel.app.DetachRequest) arg1;
        sId_ = visitor.visitString(!sId_.isEmpty(), sId_,
            !other.sId_.isEmpty(), other.sId_);
        clientId_ = visitor.visitString(!clientId_.isEmpty(), clientId_,
            !other.clientId_.isEmpty(), other.clientId_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                sId_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                clientId_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (sapphire.kernel.app.DetachRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sapphire.kernel.app.DetachRequest)
  private static final sapphire.kernel.app.DetachRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DetachRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static sapphire.kernel.app.DetachRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DetachRequest> PARSER;

  public static com.google.protobuf.Parser<DetachRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

