// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToApp.proto

package sapphire.kernel.app;

public interface InvokeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sapphire.kernel.app.InvokeRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string DMClientId = 1;</code>
   */
  java.lang.String getDMClientId();
  /**
   * <code>optional string DMClientId = 1;</code>
   */
  com.google.protobuf.ByteString
      getDMClientIdBytes();

  /**
   * <code>optional string funcName = 2;</code>
   */
  java.lang.String getFuncName();
  /**
   * <code>optional string funcName = 2;</code>
   */
  com.google.protobuf.ByteString
      getFuncNameBytes();

  /**
   * <code>optional bytes funcParams = 3;</code>
   */
  com.google.protobuf.ByteString getFuncParams();
}
