// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToApp.proto

package sapphire.kernel.app;

/**
 * Protobuf type {@code sapphire.kernel.app.InvokeRequest}
 */
public  final class InvokeRequest extends
    com.google.protobuf.GeneratedMessageLite<
        InvokeRequest, InvokeRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:sapphire.kernel.app.InvokeRequest)
    InvokeRequestOrBuilder {
  private InvokeRequest() {
    dMClientId_ = "";
    funcName_ = "";
    funcParams_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int DMCLIENTID_FIELD_NUMBER = 1;
  private java.lang.String dMClientId_;
  /**
   * <code>optional string DMClientId = 1;</code>
   */
  public java.lang.String getDMClientId() {
    return dMClientId_;
  }
  /**
   * <code>optional string DMClientId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDMClientIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(dMClientId_);
  }
  /**
   * <code>optional string DMClientId = 1;</code>
   */
  private void setDMClientId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    dMClientId_ = value;
  }
  /**
   * <code>optional string DMClientId = 1;</code>
   */
  private void clearDMClientId() {
    
    dMClientId_ = getDefaultInstance().getDMClientId();
  }
  /**
   * <code>optional string DMClientId = 1;</code>
   */
  private void setDMClientIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    dMClientId_ = value.toStringUtf8();
  }

  public static final int FUNCNAME_FIELD_NUMBER = 2;
  private java.lang.String funcName_;
  /**
   * <code>optional string funcName = 2;</code>
   */
  public java.lang.String getFuncName() {
    return funcName_;
  }
  /**
   * <code>optional string funcName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getFuncNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(funcName_);
  }
  /**
   * <code>optional string funcName = 2;</code>
   */
  private void setFuncName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    funcName_ = value;
  }
  /**
   * <code>optional string funcName = 2;</code>
   */
  private void clearFuncName() {
    
    funcName_ = getDefaultInstance().getFuncName();
  }
  /**
   * <code>optional string funcName = 2;</code>
   */
  private void setFuncNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    funcName_ = value.toStringUtf8();
  }

  public static final int FUNCPARAMS_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString funcParams_;
  /**
   * <code>optional bytes funcParams = 3;</code>
   */
  public com.google.protobuf.ByteString getFuncParams() {
    return funcParams_;
  }
  /**
   * <code>optional bytes funcParams = 3;</code>
   */
  private void setFuncParams(com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    funcParams_ = value;
  }
  /**
   * <code>optional bytes funcParams = 3;</code>
   */
  private void clearFuncParams() {
    
    funcParams_ = getDefaultInstance().getFuncParams();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!dMClientId_.isEmpty()) {
      output.writeString(1, getDMClientId());
    }
    if (!funcName_.isEmpty()) {
      output.writeString(2, getFuncName());
    }
    if (!funcParams_.isEmpty()) {
      output.writeBytes(3, funcParams_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!dMClientId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getDMClientId());
    }
    if (!funcName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getFuncName());
    }
    if (!funcParams_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, funcParams_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static sapphire.kernel.app.InvokeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.kernel.app.InvokeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.kernel.app.InvokeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.kernel.app.InvokeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.kernel.app.InvokeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.InvokeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.kernel.app.InvokeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.InvokeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.kernel.app.InvokeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.app.InvokeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sapphire.kernel.app.InvokeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code sapphire.kernel.app.InvokeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        sapphire.kernel.app.InvokeRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:sapphire.kernel.app.InvokeRequest)
      sapphire.kernel.app.InvokeRequestOrBuilder {
    // Construct using sapphire.kernel.app.InvokeRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string DMClientId = 1;</code>
     */
    public java.lang.String getDMClientId() {
      return instance.getDMClientId();
    }
    /**
     * <code>optional string DMClientId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDMClientIdBytes() {
      return instance.getDMClientIdBytes();
    }
    /**
     * <code>optional string DMClientId = 1;</code>
     */
    public Builder setDMClientId(
        java.lang.String value) {
      copyOnWrite();
      instance.setDMClientId(value);
      return this;
    }
    /**
     * <code>optional string DMClientId = 1;</code>
     */
    public Builder clearDMClientId() {
      copyOnWrite();
      instance.clearDMClientId();
      return this;
    }
    /**
     * <code>optional string DMClientId = 1;</code>
     */
    public Builder setDMClientIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDMClientIdBytes(value);
      return this;
    }

    /**
     * <code>optional string funcName = 2;</code>
     */
    public java.lang.String getFuncName() {
      return instance.getFuncName();
    }
    /**
     * <code>optional string funcName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFuncNameBytes() {
      return instance.getFuncNameBytes();
    }
    /**
     * <code>optional string funcName = 2;</code>
     */
    public Builder setFuncName(
        java.lang.String value) {
      copyOnWrite();
      instance.setFuncName(value);
      return this;
    }
    /**
     * <code>optional string funcName = 2;</code>
     */
    public Builder clearFuncName() {
      copyOnWrite();
      instance.clearFuncName();
      return this;
    }
    /**
     * <code>optional string funcName = 2;</code>
     */
    public Builder setFuncNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFuncNameBytes(value);
      return this;
    }

    /**
     * <code>optional bytes funcParams = 3;</code>
     */
    public com.google.protobuf.ByteString getFuncParams() {
      return instance.getFuncParams();
    }
    /**
     * <code>optional bytes funcParams = 3;</code>
     */
    public Builder setFuncParams(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFuncParams(value);
      return this;
    }
    /**
     * <code>optional bytes funcParams = 3;</code>
     */
    public Builder clearFuncParams() {
      copyOnWrite();
      instance.clearFuncParams();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sapphire.kernel.app.InvokeRequest)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new sapphire.kernel.app.InvokeRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        sapphire.kernel.app.InvokeRequest other = (sapphire.kernel.app.InvokeRequest) arg1;
        dMClientId_ = visitor.visitString(!dMClientId_.isEmpty(), dMClientId_,
            !other.dMClientId_.isEmpty(), other.dMClientId_);
        funcName_ = visitor.visitString(!funcName_.isEmpty(), funcName_,
            !other.funcName_.isEmpty(), other.funcName_);
        funcParams_ = visitor.visitByteString(funcParams_ != com.google.protobuf.ByteString.EMPTY, funcParams_,
            other.funcParams_ != com.google.protobuf.ByteString.EMPTY, other.funcParams_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                dMClientId_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                funcName_ = s;
                break;
              }
              case 26: {

                funcParams_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (sapphire.kernel.app.InvokeRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sapphire.kernel.app.InvokeRequest)
  private static final sapphire.kernel.app.InvokeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new InvokeRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static sapphire.kernel.app.InvokeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<InvokeRequest> PARSER;

  public static com.google.protobuf.Parser<InvokeRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

