/*
 * Stub for class sapphire.demo.KVStore
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.demo.stubs;

import sapphire.demo.KVStore;

public final class KVStore_Stub extends KVStore implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public KVStore_Stub() {
        super();
    }

    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }

    // Implementation of set(String, Serializable)
    public void set(String $param_String_1, java.io.Serializable $param_Serializable_2) {
        Object $__result = null;
        if ($__directInvocation) {
            try {
                super.set($param_String_1, $param_Serializable_2);
            } catch (Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method =
                    "public void sapphire.demo.KVStore.set(java.lang.String,java.io.Serializable)";
            $__params.add($param_String_1);
            $__params.add($param_Serializable_2);
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof RuntimeException) {
                    throw (RuntimeException) ex;
                } else {
                    throw new RuntimeException(ex);
                }
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
    }

    // Implementation of get(String)
    public java.io.Serializable get(String $param_String_1) {
        Object $__result = null;
        if ($__directInvocation) {
            try {
                $__result = super.get($param_String_1);
            } catch (Exception e) {
                throw new sapphire.common.AppExceptionWrapper(e);
            }
        } else {
            java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
            String $__method =
                    "public java.io.Serializable sapphire.demo.KVStore.get(java.lang.String)";
            $__params.add($param_String_1);
            try {
                $__result = $__client.onRPC($__method, $__params);
            } catch (sapphire.common.AppExceptionWrapper e) {
                Exception ex = e.getException();
                if (ex instanceof RuntimeException) {
                    throw (RuntimeException) ex;
                } else {
                    throw new RuntimeException(ex);
                }
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
        return ((java.io.Serializable) $__result);
    }
}
