// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToRuntime.proto

package sapphire.kernel.runtime;

/**
 * Protobuf type {@code sapphire.kernel.runtime.CreateChildSObjResponse}
 */
public  final class CreateChildSObjResponse extends
    com.google.protobuf.GeneratedMessageLite<
        CreateChildSObjResponse, CreateChildSObjResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:sapphire.kernel.runtime.CreateChildSObjResponse)
    CreateChildSObjResponseOrBuilder {
  private CreateChildSObjResponse() {
    sObjId_ = "";
    sObjReplicaId_ = "";
  }
  public static final int SOBJID_FIELD_NUMBER = 1;
  private java.lang.String sObjId_;
  /**
   * <code>optional string sObjId = 1;</code>
   */
  public java.lang.String getSObjId() {
    return sObjId_;
  }
  /**
   * <code>optional string sObjId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSObjIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sObjId_);
  }
  /**
   * <code>optional string sObjId = 1;</code>
   */
  private void setSObjId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    sObjId_ = value;
  }
  /**
   * <code>optional string sObjId = 1;</code>
   */
  private void clearSObjId() {
    
    sObjId_ = getDefaultInstance().getSObjId();
  }
  /**
   * <code>optional string sObjId = 1;</code>
   */
  private void setSObjIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    sObjId_ = value.toStringUtf8();
  }

  public static final int SOBJREPLICAID_FIELD_NUMBER = 2;
  private java.lang.String sObjReplicaId_;
  /**
   * <code>optional string sObjReplicaId = 2;</code>
   */
  public java.lang.String getSObjReplicaId() {
    return sObjReplicaId_;
  }
  /**
   * <code>optional string sObjReplicaId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSObjReplicaIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sObjReplicaId_);
  }
  /**
   * <code>optional string sObjReplicaId = 2;</code>
   */
  private void setSObjReplicaId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    sObjReplicaId_ = value;
  }
  /**
   * <code>optional string sObjReplicaId = 2;</code>
   */
  private void clearSObjReplicaId() {
    
    sObjReplicaId_ = getDefaultInstance().getSObjReplicaId();
  }
  /**
   * <code>optional string sObjReplicaId = 2;</code>
   */
  private void setSObjReplicaIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    sObjReplicaId_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!sObjId_.isEmpty()) {
      output.writeString(1, getSObjId());
    }
    if (!sObjReplicaId_.isEmpty()) {
      output.writeString(2, getSObjReplicaId());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!sObjId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getSObjId());
    }
    if (!sObjReplicaId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getSObjReplicaId());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static sapphire.kernel.runtime.CreateChildSObjResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.kernel.runtime.CreateChildSObjResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.kernel.runtime.CreateChildSObjResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.kernel.runtime.CreateChildSObjResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.kernel.runtime.CreateChildSObjResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.runtime.CreateChildSObjResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.kernel.runtime.CreateChildSObjResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.runtime.CreateChildSObjResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.kernel.runtime.CreateChildSObjResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.runtime.CreateChildSObjResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sapphire.kernel.runtime.CreateChildSObjResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code sapphire.kernel.runtime.CreateChildSObjResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        sapphire.kernel.runtime.CreateChildSObjResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:sapphire.kernel.runtime.CreateChildSObjResponse)
      sapphire.kernel.runtime.CreateChildSObjResponseOrBuilder {
    // Construct using sapphire.kernel.runtime.CreateChildSObjResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string sObjId = 1;</code>
     */
    public java.lang.String getSObjId() {
      return instance.getSObjId();
    }
    /**
     * <code>optional string sObjId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSObjIdBytes() {
      return instance.getSObjIdBytes();
    }
    /**
     * <code>optional string sObjId = 1;</code>
     */
    public Builder setSObjId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSObjId(value);
      return this;
    }
    /**
     * <code>optional string sObjId = 1;</code>
     */
    public Builder clearSObjId() {
      copyOnWrite();
      instance.clearSObjId();
      return this;
    }
    /**
     * <code>optional string sObjId = 1;</code>
     */
    public Builder setSObjIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSObjIdBytes(value);
      return this;
    }

    /**
     * <code>optional string sObjReplicaId = 2;</code>
     */
    public java.lang.String getSObjReplicaId() {
      return instance.getSObjReplicaId();
    }
    /**
     * <code>optional string sObjReplicaId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSObjReplicaIdBytes() {
      return instance.getSObjReplicaIdBytes();
    }
    /**
     * <code>optional string sObjReplicaId = 2;</code>
     */
    public Builder setSObjReplicaId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSObjReplicaId(value);
      return this;
    }
    /**
     * <code>optional string sObjReplicaId = 2;</code>
     */
    public Builder clearSObjReplicaId() {
      copyOnWrite();
      instance.clearSObjReplicaId();
      return this;
    }
    /**
     * <code>optional string sObjReplicaId = 2;</code>
     */
    public Builder setSObjReplicaIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSObjReplicaIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sapphire.kernel.runtime.CreateChildSObjResponse)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new sapphire.kernel.runtime.CreateChildSObjResponse();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        sapphire.kernel.runtime.CreateChildSObjResponse other = (sapphire.kernel.runtime.CreateChildSObjResponse) arg1;
        sObjId_ = visitor.visitString(!sObjId_.isEmpty(), sObjId_,
            !other.sObjId_.isEmpty(), other.sObjId_);
        sObjReplicaId_ = visitor.visitString(!sObjReplicaId_.isEmpty(), sObjReplicaId_,
            !other.sObjReplicaId_.isEmpty(), other.sObjReplicaId_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                sObjId_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                sObjReplicaId_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (sapphire.kernel.runtime.CreateChildSObjResponse.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sapphire.kernel.runtime.CreateChildSObjResponse)
  private static final sapphire.kernel.runtime.CreateChildSObjResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CreateChildSObjResponse();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static sapphire.kernel.runtime.CreateChildSObjResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CreateChildSObjResponse> PARSER;

  public static com.google.protobuf.Parser<CreateChildSObjResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

