// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToRuntime.proto

package sapphire.kernel.runtime;

/**
 * Protobuf type {@code sapphire.kernel.runtime.DeleteChildSObjResponse}
 */
public  final class DeleteChildSObjResponse extends
    com.google.protobuf.GeneratedMessageLite<
        DeleteChildSObjResponse, DeleteChildSObjResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:sapphire.kernel.runtime.DeleteChildSObjResponse)
    DeleteChildSObjResponseOrBuilder {
  private DeleteChildSObjResponse() {
  }
  public static final int STATUS_FIELD_NUMBER = 1;
  private boolean status_;
  /**
   * <code>optional bool status = 1;</code>
   */
  public boolean getStatus() {
    return status_;
  }
  /**
   * <code>optional bool status = 1;</code>
   */
  private void setStatus(boolean value) {
    
    status_ = value;
  }
  /**
   * <code>optional bool status = 1;</code>
   */
  private void clearStatus() {
    
    status_ = false;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != false) {
      output.writeBool(1, status_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, status_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static sapphire.kernel.runtime.DeleteChildSObjResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.kernel.runtime.DeleteChildSObjResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.kernel.runtime.DeleteChildSObjResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.kernel.runtime.DeleteChildSObjResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.kernel.runtime.DeleteChildSObjResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.runtime.DeleteChildSObjResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.kernel.runtime.DeleteChildSObjResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.runtime.DeleteChildSObjResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.kernel.runtime.DeleteChildSObjResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.kernel.runtime.DeleteChildSObjResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sapphire.kernel.runtime.DeleteChildSObjResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code sapphire.kernel.runtime.DeleteChildSObjResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        sapphire.kernel.runtime.DeleteChildSObjResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:sapphire.kernel.runtime.DeleteChildSObjResponse)
      sapphire.kernel.runtime.DeleteChildSObjResponseOrBuilder {
    // Construct using sapphire.kernel.runtime.DeleteChildSObjResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional bool status = 1;</code>
     */
    public boolean getStatus() {
      return instance.getStatus();
    }
    /**
     * <code>optional bool status = 1;</code>
     */
    public Builder setStatus(boolean value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
    }
    /**
     * <code>optional bool status = 1;</code>
     */
    public Builder clearStatus() {
      copyOnWrite();
      instance.clearStatus();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sapphire.kernel.runtime.DeleteChildSObjResponse)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new sapphire.kernel.runtime.DeleteChildSObjResponse();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        sapphire.kernel.runtime.DeleteChildSObjResponse other = (sapphire.kernel.runtime.DeleteChildSObjResponse) arg1;
        status_ = visitor.visitBoolean(status_ != false, status_,
            other.status_ != false, other.status_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                status_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (sapphire.kernel.runtime.DeleteChildSObjResponse.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sapphire.kernel.runtime.DeleteChildSObjResponse)
  private static final sapphire.kernel.runtime.DeleteChildSObjResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DeleteChildSObjResponse();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static sapphire.kernel.runtime.DeleteChildSObjResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DeleteChildSObjResponse> PARSER;

  public static com.google.protobuf.Parser<DeleteChildSObjResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

