// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KernelServerApiToRuntime.proto

package sapphire.kernel.runtime;

public interface DMInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sapphire.kernel.runtime.DMInfo)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string clientPolicy = 1;</code>
   */
  java.lang.String getClientPolicy();
  /**
   * <code>optional string clientPolicy = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientPolicyBytes();

  /**
   * <code>optional string serverPolicy = 2;</code>
   */
  java.lang.String getServerPolicy();
  /**
   * <code>optional string serverPolicy = 2;</code>
   */
  com.google.protobuf.ByteString
      getServerPolicyBytes();

  /**
   * <code>optional string groupPolicy = 3;</code>
   */
  java.lang.String getGroupPolicy();
  /**
   * <code>optional string groupPolicy = 3;</code>
   */
  com.google.protobuf.ByteString
      getGroupPolicyBytes();
}
