// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TodoList.proto

package hankstodo.app;

public final class TodoListOuterClass {
  private TodoListOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface TodoListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hankstodo_app.TodoList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string sid = 1;</code>
     */
    java.lang.String getSid();
    /**
     * <code>optional string sid = 1;</code>
     */
    com.google.protobuf.ByteString
        getSidBytes();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code hankstodo_app.TodoList}
   */
  public  static final class TodoList extends
      com.google.protobuf.GeneratedMessageLite<
          TodoList, TodoList.Builder> implements
      // @@protoc_insertion_point(message_implements:hankstodo_app.TodoList)
      TodoListOrBuilder {
    private TodoList() {
      sid_ = "";
      name_ = "";
    }
    public static final int SID_FIELD_NUMBER = 1;
    private java.lang.String sid_;
    /**
     * <code>optional string sid = 1;</code>
     */
    public java.lang.String getSid() {
      return sid_;
    }
    /**
     * <code>optional string sid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sid_);
    }
    /**
     * <code>optional string sid = 1;</code>
     */
    private void setSid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sid_ = value;
    }
    /**
     * <code>optional string sid = 1;</code>
     */
    private void clearSid() {
      
      sid_ = getDefaultInstance().getSid();
    }
    /**
     * <code>optional string sid = 1;</code>
     */
    private void setSidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sid_ = value.toStringUtf8();
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.String name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    private void setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>optional string name = 2;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!sid_.isEmpty()) {
        output.writeString(1, getSid());
      }
      if (!name_.isEmpty()) {
        output.writeString(2, getName());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!sid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSid());
      }
      if (!name_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static hankstodo.app.TodoListOuterClass.TodoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static hankstodo.app.TodoListOuterClass.TodoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static hankstodo.app.TodoListOuterClass.TodoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static hankstodo.app.TodoListOuterClass.TodoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static hankstodo.app.TodoListOuterClass.TodoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListOuterClass.TodoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static hankstodo.app.TodoListOuterClass.TodoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListOuterClass.TodoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static hankstodo.app.TodoListOuterClass.TodoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListOuterClass.TodoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hankstodo.app.TodoListOuterClass.TodoList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code hankstodo_app.TodoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          hankstodo.app.TodoListOuterClass.TodoList, Builder> implements
        // @@protoc_insertion_point(builder_implements:hankstodo_app.TodoList)
        hankstodo.app.TodoListOuterClass.TodoListOrBuilder {
      // Construct using hankstodo.app.TodoListOuterClass.TodoList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string sid = 1;</code>
       */
      public java.lang.String getSid() {
        return instance.getSid();
      }
      /**
       * <code>optional string sid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSidBytes() {
        return instance.getSidBytes();
      }
      /**
       * <code>optional string sid = 1;</code>
       */
      public Builder setSid(
          java.lang.String value) {
        copyOnWrite();
        instance.setSid(value);
        return this;
      }
      /**
       * <code>optional string sid = 1;</code>
       */
      public Builder clearSid() {
        copyOnWrite();
        instance.clearSid();
        return this;
      }
      /**
       * <code>optional string sid = 1;</code>
       */
      public Builder setSidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSidBytes(value);
        return this;
      }

      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hankstodo_app.TodoList)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new hankstodo.app.TodoListOuterClass.TodoList();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          hankstodo.app.TodoListOuterClass.TodoList other = (hankstodo.app.TodoListOuterClass.TodoList) arg1;
          sid_ = visitor.visitString(!sid_.isEmpty(), sid_,
              !other.sid_.isEmpty(), other.sid_);
          name_ = visitor.visitString(!name_.isEmpty(), name_,
              !other.name_.isEmpty(), other.name_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  sid_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (hankstodo.app.TodoListOuterClass.TodoList.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:hankstodo_app.TodoList)
    private static final hankstodo.app.TodoListOuterClass.TodoList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TodoList();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static hankstodo.app.TodoListOuterClass.TodoList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<TodoList> PARSER;

    public static com.google.protobuf.Parser<TodoList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface inAddToDoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hankstodo_app.inAddToDo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string arg0 = 1;</code>
     */
    java.lang.String getArg0();
    /**
     * <code>optional string arg0 = 1;</code>
     */
    com.google.protobuf.ByteString
        getArg0Bytes();
  }
  /**
   * Protobuf type {@code hankstodo_app.inAddToDo}
   */
  public  static final class inAddToDo extends
      com.google.protobuf.GeneratedMessageLite<
          inAddToDo, inAddToDo.Builder> implements
      // @@protoc_insertion_point(message_implements:hankstodo_app.inAddToDo)
      inAddToDoOrBuilder {
    private inAddToDo() {
      arg0_ = "";
    }
    public static final int ARG0_FIELD_NUMBER = 1;
    private java.lang.String arg0_;
    /**
     * <code>optional string arg0 = 1;</code>
     */
    public java.lang.String getArg0() {
      return arg0_;
    }
    /**
     * <code>optional string arg0 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getArg0Bytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(arg0_);
    }
    /**
     * <code>optional string arg0 = 1;</code>
     */
    private void setArg0(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      arg0_ = value;
    }
    /**
     * <code>optional string arg0 = 1;</code>
     */
    private void clearArg0() {
      
      arg0_ = getDefaultInstance().getArg0();
    }
    /**
     * <code>optional string arg0 = 1;</code>
     */
    private void setArg0Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      arg0_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!arg0_.isEmpty()) {
        output.writeString(1, getArg0());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!arg0_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getArg0());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static hankstodo.app.TodoListOuterClass.inAddToDo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static hankstodo.app.TodoListOuterClass.inAddToDo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static hankstodo.app.TodoListOuterClass.inAddToDo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static hankstodo.app.TodoListOuterClass.inAddToDo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static hankstodo.app.TodoListOuterClass.inAddToDo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListOuterClass.inAddToDo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static hankstodo.app.TodoListOuterClass.inAddToDo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListOuterClass.inAddToDo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static hankstodo.app.TodoListOuterClass.inAddToDo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListOuterClass.inAddToDo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hankstodo.app.TodoListOuterClass.inAddToDo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code hankstodo_app.inAddToDo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          hankstodo.app.TodoListOuterClass.inAddToDo, Builder> implements
        // @@protoc_insertion_point(builder_implements:hankstodo_app.inAddToDo)
        hankstodo.app.TodoListOuterClass.inAddToDoOrBuilder {
      // Construct using hankstodo.app.TodoListOuterClass.inAddToDo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string arg0 = 1;</code>
       */
      public java.lang.String getArg0() {
        return instance.getArg0();
      }
      /**
       * <code>optional string arg0 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getArg0Bytes() {
        return instance.getArg0Bytes();
      }
      /**
       * <code>optional string arg0 = 1;</code>
       */
      public Builder setArg0(
          java.lang.String value) {
        copyOnWrite();
        instance.setArg0(value);
        return this;
      }
      /**
       * <code>optional string arg0 = 1;</code>
       */
      public Builder clearArg0() {
        copyOnWrite();
        instance.clearArg0();
        return this;
      }
      /**
       * <code>optional string arg0 = 1;</code>
       */
      public Builder setArg0Bytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setArg0Bytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hankstodo_app.inAddToDo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new hankstodo.app.TodoListOuterClass.inAddToDo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          hankstodo.app.TodoListOuterClass.inAddToDo other = (hankstodo.app.TodoListOuterClass.inAddToDo) arg1;
          arg0_ = visitor.visitString(!arg0_.isEmpty(), arg0_,
              !other.arg0_.isEmpty(), other.arg0_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  arg0_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (hankstodo.app.TodoListOuterClass.inAddToDo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:hankstodo_app.inAddToDo)
    private static final hankstodo.app.TodoListOuterClass.inAddToDo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new inAddToDo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static hankstodo.app.TodoListOuterClass.inAddToDo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<inAddToDo> PARSER;

    public static com.google.protobuf.Parser<inAddToDo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface outAddToDoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hankstodo_app.outAddToDo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string arg0 = 1;</code>
     */
    java.lang.String getArg0();
    /**
     * <code>optional string arg0 = 1;</code>
     */
    com.google.protobuf.ByteString
        getArg0Bytes();
  }
  /**
   * Protobuf type {@code hankstodo_app.outAddToDo}
   */
  public  static final class outAddToDo extends
      com.google.protobuf.GeneratedMessageLite<
          outAddToDo, outAddToDo.Builder> implements
      // @@protoc_insertion_point(message_implements:hankstodo_app.outAddToDo)
      outAddToDoOrBuilder {
    private outAddToDo() {
      arg0_ = "";
    }
    public static final int ARG0_FIELD_NUMBER = 1;
    private java.lang.String arg0_;
    /**
     * <code>optional string arg0 = 1;</code>
     */
    public java.lang.String getArg0() {
      return arg0_;
    }
    /**
     * <code>optional string arg0 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getArg0Bytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(arg0_);
    }
    /**
     * <code>optional string arg0 = 1;</code>
     */
    private void setArg0(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      arg0_ = value;
    }
    /**
     * <code>optional string arg0 = 1;</code>
     */
    private void clearArg0() {
      
      arg0_ = getDefaultInstance().getArg0();
    }
    /**
     * <code>optional string arg0 = 1;</code>
     */
    private void setArg0Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      arg0_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!arg0_.isEmpty()) {
        output.writeString(1, getArg0());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!arg0_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getArg0());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static hankstodo.app.TodoListOuterClass.outAddToDo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static hankstodo.app.TodoListOuterClass.outAddToDo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static hankstodo.app.TodoListOuterClass.outAddToDo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static hankstodo.app.TodoListOuterClass.outAddToDo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static hankstodo.app.TodoListOuterClass.outAddToDo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListOuterClass.outAddToDo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static hankstodo.app.TodoListOuterClass.outAddToDo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListOuterClass.outAddToDo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static hankstodo.app.TodoListOuterClass.outAddToDo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static hankstodo.app.TodoListOuterClass.outAddToDo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hankstodo.app.TodoListOuterClass.outAddToDo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code hankstodo_app.outAddToDo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          hankstodo.app.TodoListOuterClass.outAddToDo, Builder> implements
        // @@protoc_insertion_point(builder_implements:hankstodo_app.outAddToDo)
        hankstodo.app.TodoListOuterClass.outAddToDoOrBuilder {
      // Construct using hankstodo.app.TodoListOuterClass.outAddToDo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string arg0 = 1;</code>
       */
      public java.lang.String getArg0() {
        return instance.getArg0();
      }
      /**
       * <code>optional string arg0 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getArg0Bytes() {
        return instance.getArg0Bytes();
      }
      /**
       * <code>optional string arg0 = 1;</code>
       */
      public Builder setArg0(
          java.lang.String value) {
        copyOnWrite();
        instance.setArg0(value);
        return this;
      }
      /**
       * <code>optional string arg0 = 1;</code>
       */
      public Builder clearArg0() {
        copyOnWrite();
        instance.clearArg0();
        return this;
      }
      /**
       * <code>optional string arg0 = 1;</code>
       */
      public Builder setArg0Bytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setArg0Bytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hankstodo_app.outAddToDo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new hankstodo.app.TodoListOuterClass.outAddToDo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          hankstodo.app.TodoListOuterClass.outAddToDo other = (hankstodo.app.TodoListOuterClass.outAddToDo) arg1;
          arg0_ = visitor.visitString(!arg0_.isEmpty(), arg0_,
              !other.arg0_.isEmpty(), other.arg0_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  arg0_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (hankstodo.app.TodoListOuterClass.outAddToDo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:hankstodo_app.outAddToDo)
    private static final hankstodo.app.TodoListOuterClass.outAddToDo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new outAddToDo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static hankstodo.app.TodoListOuterClass.outAddToDo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<outAddToDo> PARSER;

    public static com.google.protobuf.Parser<outAddToDo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
