/*
 * Stub for class sapphire.policy.replication.ConsensusRSMPolicy.ServerPolicy
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.policy.stubs;


public final class ConsensusRSMPolicy$ServerPolicy_Stub extends sapphire.policy.replication.ConsensusRSMPolicy.ServerPolicy implements sapphire.kernel.common.KernelObjectStub {

    sapphire.kernel.common.KernelOID $__oid = null;
    java.net.InetSocketAddress $__hostname = null;

    public ConsensusRSMPolicy$ServerPolicy_Stub(sapphire.kernel.common.KernelOID oid) {
        this.$__oid = oid;
    }

    public sapphire.kernel.common.KernelOID $__getKernelOID() {
        return this.$__oid;
    }

    public java.net.InetSocketAddress $__getHostname() {
        return this.$__hostname;
    }

    public void $__updateHostname(java.net.InetSocketAddress hostname) {
        this.$__hostname = hostname;
    }

    public Object $__makeKernelRPC(java.lang.String method, java.util.ArrayList<Object> params) throws java.rmi.RemoteException, java.lang.Exception {
        sapphire.kernel.common.KernelRPC rpc = new sapphire.kernel.common.KernelRPC($__oid, method, params);
        try {
            return sapphire.kernel.common.GlobalKernelReferences.nodeServer.getKernelClient().makeKernelRPC(this, rpc);
        } catch (sapphire.kernel.common.KernelObjectNotFoundException e) {
            throw new java.rmi.RemoteException();
        }
    }

    @Override
    public boolean equals(Object obj) { 
        ConsensusRSMPolicy$ServerPolicy_Stub other = (ConsensusRSMPolicy$ServerPolicy_Stub) obj;
        if (! other.$__oid.equals($__oid))
            return false;
        return true;
    }
    @Override
    public int hashCode() { 
        return $__oid.getID();
    }


    // Implementation of sapphire_replicate()
    public sapphire.policy.SapphirePolicy.SapphireServerPolicy sapphire_replicate() {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public sapphire.policy.SapphirePolicy$SapphireServerPolicy sapphire.policy.DefaultSapphirePolicyUpcallImpl$DefaultSapphireServerPolicyUpcallImpl.sapphire_replicate()";
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.policy.SapphirePolicy.SapphireServerPolicy) $__result);
    }

    // Implementation of sapphire_pin_to_server(InetSocketAddress)
    public void sapphire_pin_to_server(java.net.InetSocketAddress $param_InetSocketAddress_1)
            throws java.rmi.RemoteException {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.DefaultSapphirePolicyUpcallImpl$DefaultSapphireServerPolicyUpcallImpl.sapphire_pin_to_server(java.net.InetSocketAddress) throws java.rmi.RemoteException";
        $__params.add($param_InetSocketAddress_1);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of sapphire_pin(String)
    public void sapphire_pin(java.lang.String $param_String_1)
            throws java.rmi.RemoteException {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.DefaultSapphirePolicyUpcallImpl$DefaultSapphireServerPolicyUpcallImpl.sapphire_pin(java.lang.String) throws java.rmi.RemoteException";
        $__params.add($param_String_1);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of requestVote(int, UUID, int, int)
    public int requestVote(int $param_int_1, java.util.UUID $param_UUID_2, int $param_int_3, int $param_int_4)
            throws sapphire.policy.util.consensus.raft.Server$InvalidTermException, sapphire.policy.util.consensus.raft.Server$AlreadyVotedException, sapphire.policy.util.consensus.raft.Server$CandidateBehindException {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public int sapphire.policy.replication.ConsensusRSMPolicy$ServerPolicy.requestVote(int,java.util.UUID,int,int) throws sapphire.policy.util.consensus.raft.Server$InvalidTermException,sapphire.policy.util.consensus.raft.Server$AlreadyVotedException,sapphire.policy.util.consensus.raft.Server$CandidateBehindException";
        $__params.add($param_int_1);
        $__params.add($param_UUID_2);
        $__params.add($param_int_3);
        $__params.add($param_int_4);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Integer) $__result).intValue();
    }

    // Implementation of onRPC(String, ArrayList)
    public java.lang.Object onRPC(java.lang.String $param_String_1, java.util.ArrayList $param_ArrayList_2)
            throws java.lang.Exception {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public java.lang.Object sapphire.policy.replication.ConsensusRSMPolicy$ServerPolicy.onRPC(java.lang.String,java.util.ArrayList<java.lang.Object>) throws java.lang.Exception";
        $__params.add($param_String_1);
        $__params.add($param_ArrayList_2);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return $__result;
    }

    // Implementation of onMembershipChange()
    public void onMembershipChange() {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.DefaultSapphirePolicy$DefaultServerPolicy.onMembershipChange()";
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of onCreate(SapphirePolicy.SapphireGroupPolicy)
    public void onCreate(sapphire.policy.SapphirePolicy.SapphireGroupPolicy $param_SapphirePolicy$SapphireGroupPolicy_1) {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.replication.ConsensusRSMPolicy$ServerPolicy.onCreate(sapphire.policy.SapphirePolicy$SapphireGroupPolicy)";
        $__params.add($param_SapphirePolicy$SapphireGroupPolicy_1);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of initializeRaftServer()
    public void initializeRaftServer() {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.replication.ConsensusRSMPolicy$ServerPolicy.initializeRaftServer()";
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of initializeRaft(ConcurrentMap)
    public void initializeRaft(java.util.concurrent.ConcurrentMap $param_ConcurrentMap_1) {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public void sapphire.policy.replication.ConsensusRSMPolicy$ServerPolicy.initializeRaft(java.util.concurrent.ConcurrentMap<java.util.UUID, sapphire.policy.replication.ConsensusRSMPolicy$ServerPolicy>)";
        $__params.add($param_ConcurrentMap_1);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of getRaftServer()
    public sapphire.policy.util.consensus.raft.Server getRaftServer() {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public sapphire.policy.util.consensus.raft.Server sapphire.policy.replication.ConsensusRSMPolicy$ServerPolicy.getRaftServer()";
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.policy.util.consensus.raft.Server) $__result);
    }

    // Implementation of getGroup()
    public sapphire.policy.SapphirePolicy.SapphireGroupPolicy getGroup() {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public sapphire.policy.SapphirePolicy$SapphireGroupPolicy sapphire.policy.DefaultSapphirePolicy$DefaultServerPolicy.getGroup()";
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.policy.SapphirePolicy.SapphireGroupPolicy) $__result);
    }

    // Implementation of applyToStateMachine(Object)
    public java.lang.Object applyToStateMachine(java.lang.Object $param_Object_1)
            throws java.lang.Exception {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public java.lang.Object sapphire.policy.replication.ConsensusRSMPolicy$ServerPolicy.applyToStateMachine(java.lang.Object) throws java.lang.Exception";
        $__params.add($param_Object_1);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return $__result;
    }

    // Implementation of apply(Object)
    public java.lang.Object apply(java.lang.Object $param_Object_1)
            throws java.lang.Exception {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public java.lang.Object sapphire.policy.replication.ConsensusRSMPolicy$ServerPolicy.apply(java.lang.Object) throws java.lang.Exception";
        $__params.add($param_Object_1);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return $__result;
    }

    // Implementation of appendEntries(int, UUID, int, int, List, int)
    public int appendEntries(int $param_int_1, java.util.UUID $param_UUID_2, int $param_int_3, int $param_int_4, java.util.List $param_List_5, int $param_int_6)
            throws sapphire.policy.util.consensus.raft.Server$InvalidTermException, sapphire.policy.util.consensus.raft.Server$PrevLogTermMismatch, sapphire.policy.util.consensus.raft.Server$InvalidLogIndex {
        java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
        String $__method = "public int sapphire.policy.replication.ConsensusRSMPolicy$ServerPolicy.appendEntries(int,java.util.UUID,int,int,java.util.List<sapphire.policy.util.consensus.raft.LogEntry>,int) throws sapphire.policy.util.consensus.raft.Server$InvalidTermException,sapphire.policy.util.consensus.raft.Server$PrevLogTermMismatch,sapphire.policy.util.consensus.raft.Server$InvalidLogIndex";
        $__params.add($param_int_1);
        $__params.add($param_UUID_2);
        $__params.add($param_int_3);
        $__params.add($param_int_4);
        $__params.add($param_List_5);
        $__params.add($param_int_6);
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Integer) $__result).intValue();
    }
}
