// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RuntimeApiToKernelServer.proto

package sapphire_runtime_kernel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateSObjReplicaRequest struct {
	SObjName              string   `protobuf:"bytes,1,opt,name=sObjName,proto3" json:"sObjName,omitempty"`
	SObjConstructorName   string   `protobuf:"bytes,2,opt,name=sObjConstructorName,proto3" json:"sObjConstructorName,omitempty"`
	SObjConstructorParams []byte   `protobuf:"bytes,3,opt,name=sObjConstructorParams,proto3" json:"sObjConstructorParams,omitempty"`
	SObjParentSObjId      string   `protobuf:"bytes,4,opt,name=sObjParentSObjId,proto3" json:"sObjParentSObjId,omitempty"`
	SObjId                string   `protobuf:"bytes,5,opt,name=sObjId,proto3" json:"sObjId,omitempty"`
	SObjReplicaId         string   `protobuf:"bytes,6,opt,name=sObjReplicaId,proto3" json:"sObjReplicaId,omitempty"`
	SObjReplicaObject     []byte   `protobuf:"bytes,7,opt,name=sObjReplicaObject,proto3" json:"sObjReplicaObject,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CreateSObjReplicaRequest) Reset()         { *m = CreateSObjReplicaRequest{} }
func (m *CreateSObjReplicaRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSObjReplicaRequest) ProtoMessage()    {}
func (*CreateSObjReplicaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_RuntimeApiToKernelServer_f28af194d1f8932e, []int{0}
}
func (m *CreateSObjReplicaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSObjReplicaRequest.Unmarshal(m, b)
}
func (m *CreateSObjReplicaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSObjReplicaRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSObjReplicaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSObjReplicaRequest.Merge(dst, src)
}
func (m *CreateSObjReplicaRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSObjReplicaRequest.Size(m)
}
func (m *CreateSObjReplicaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSObjReplicaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSObjReplicaRequest proto.InternalMessageInfo

func (m *CreateSObjReplicaRequest) GetSObjName() string {
	if m != nil {
		return m.SObjName
	}
	return ""
}

func (m *CreateSObjReplicaRequest) GetSObjConstructorName() string {
	if m != nil {
		return m.SObjConstructorName
	}
	return ""
}

func (m *CreateSObjReplicaRequest) GetSObjConstructorParams() []byte {
	if m != nil {
		return m.SObjConstructorParams
	}
	return nil
}

func (m *CreateSObjReplicaRequest) GetSObjParentSObjId() string {
	if m != nil {
		return m.SObjParentSObjId
	}
	return ""
}

func (m *CreateSObjReplicaRequest) GetSObjId() string {
	if m != nil {
		return m.SObjId
	}
	return ""
}

func (m *CreateSObjReplicaRequest) GetSObjReplicaId() string {
	if m != nil {
		return m.SObjReplicaId
	}
	return ""
}

func (m *CreateSObjReplicaRequest) GetSObjReplicaObject() []byte {
	if m != nil {
		return m.SObjReplicaObject
	}
	return nil
}

type DMInfo struct {
	ClientPolicy         string   `protobuf:"bytes,1,opt,name=clientPolicy,proto3" json:"clientPolicy,omitempty"`
	ServerPolicy         string   `protobuf:"bytes,2,opt,name=serverPolicy,proto3" json:"serverPolicy,omitempty"`
	GroupPolicy          string   `protobuf:"bytes,3,opt,name=groupPolicy,proto3" json:"groupPolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DMInfo) Reset()         { *m = DMInfo{} }
func (m *DMInfo) String() string { return proto.CompactTextString(m) }
func (*DMInfo) ProtoMessage()    {}
func (*DMInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_RuntimeApiToKernelServer_f28af194d1f8932e, []int{1}
}
func (m *DMInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DMInfo.Unmarshal(m, b)
}
func (m *DMInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DMInfo.Marshal(b, m, deterministic)
}
func (dst *DMInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DMInfo.Merge(dst, src)
}
func (m *DMInfo) XXX_Size() int {
	return xxx_messageInfo_DMInfo.Size(m)
}
func (m *DMInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DMInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DMInfo proto.InternalMessageInfo

func (m *DMInfo) GetClientPolicy() string {
	if m != nil {
		return m.ClientPolicy
	}
	return ""
}

func (m *DMInfo) GetServerPolicy() string {
	if m != nil {
		return m.ServerPolicy
	}
	return ""
}

func (m *DMInfo) GetGroupPolicy() string {
	if m != nil {
		return m.GroupPolicy
	}
	return ""
}

type CreateSObjReplicaResponse struct {
	SObjReplicaObject    []byte   `protobuf:"bytes,1,opt,name=sObjReplicaObject,proto3" json:"sObjReplicaObject,omitempty"`
	SObjDMInfo           *DMInfo  `protobuf:"bytes,2,opt,name=sObjDMInfo,proto3" json:"sObjDMInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSObjReplicaResponse) Reset()         { *m = CreateSObjReplicaResponse{} }
func (m *CreateSObjReplicaResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSObjReplicaResponse) ProtoMessage()    {}
func (*CreateSObjReplicaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_RuntimeApiToKernelServer_f28af194d1f8932e, []int{2}
}
func (m *CreateSObjReplicaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSObjReplicaResponse.Unmarshal(m, b)
}
func (m *CreateSObjReplicaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSObjReplicaResponse.Marshal(b, m, deterministic)
}
func (dst *CreateSObjReplicaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSObjReplicaResponse.Merge(dst, src)
}
func (m *CreateSObjReplicaResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSObjReplicaResponse.Size(m)
}
func (m *CreateSObjReplicaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSObjReplicaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSObjReplicaResponse proto.InternalMessageInfo

func (m *CreateSObjReplicaResponse) GetSObjReplicaObject() []byte {
	if m != nil {
		return m.SObjReplicaObject
	}
	return nil
}

func (m *CreateSObjReplicaResponse) GetSObjDMInfo() *DMInfo {
	if m != nil {
		return m.SObjDMInfo
	}
	return nil
}

type DeleteSObjReplicaRequest struct {
	SObjId               string   `protobuf:"bytes,1,opt,name=sObjId,proto3" json:"sObjId,omitempty"`
	SObjReplicaId        string   `protobuf:"bytes,2,opt,name=sObjReplicaId,proto3" json:"sObjReplicaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSObjReplicaRequest) Reset()         { *m = DeleteSObjReplicaRequest{} }
func (m *DeleteSObjReplicaRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSObjReplicaRequest) ProtoMessage()    {}
func (*DeleteSObjReplicaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_RuntimeApiToKernelServer_f28af194d1f8932e, []int{3}
}
func (m *DeleteSObjReplicaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSObjReplicaRequest.Unmarshal(m, b)
}
func (m *DeleteSObjReplicaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSObjReplicaRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteSObjReplicaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSObjReplicaRequest.Merge(dst, src)
}
func (m *DeleteSObjReplicaRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSObjReplicaRequest.Size(m)
}
func (m *DeleteSObjReplicaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSObjReplicaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSObjReplicaRequest proto.InternalMessageInfo

func (m *DeleteSObjReplicaRequest) GetSObjId() string {
	if m != nil {
		return m.SObjId
	}
	return ""
}

func (m *DeleteSObjReplicaRequest) GetSObjReplicaId() string {
	if m != nil {
		return m.SObjReplicaId
	}
	return ""
}

type DeleteSObjReplicaResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSObjReplicaResponse) Reset()         { *m = DeleteSObjReplicaResponse{} }
func (m *DeleteSObjReplicaResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSObjReplicaResponse) ProtoMessage()    {}
func (*DeleteSObjReplicaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_RuntimeApiToKernelServer_f28af194d1f8932e, []int{4}
}
func (m *DeleteSObjReplicaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSObjReplicaResponse.Unmarshal(m, b)
}
func (m *DeleteSObjReplicaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSObjReplicaResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteSObjReplicaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSObjReplicaResponse.Merge(dst, src)
}
func (m *DeleteSObjReplicaResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSObjReplicaResponse.Size(m)
}
func (m *DeleteSObjReplicaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSObjReplicaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSObjReplicaResponse proto.InternalMessageInfo

func (m *DeleteSObjReplicaResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type SObjMethodInvokeRequest struct {
	SObjId               string   `protobuf:"bytes,1,opt,name=sObjId,proto3" json:"sObjId,omitempty"`
	SObjReplicaId        string   `protobuf:"bytes,2,opt,name=sObjReplicaId,proto3" json:"sObjReplicaId,omitempty"`
	SObjMethodName       string   `protobuf:"bytes,3,opt,name=sObjMethodName,proto3" json:"sObjMethodName,omitempty"`
	SObjMethodParams     []byte   `protobuf:"bytes,4,opt,name=sObjMethodParams,proto3" json:"sObjMethodParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SObjMethodInvokeRequest) Reset()         { *m = SObjMethodInvokeRequest{} }
func (m *SObjMethodInvokeRequest) String() string { return proto.CompactTextString(m) }
func (*SObjMethodInvokeRequest) ProtoMessage()    {}
func (*SObjMethodInvokeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_RuntimeApiToKernelServer_f28af194d1f8932e, []int{5}
}
func (m *SObjMethodInvokeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SObjMethodInvokeRequest.Unmarshal(m, b)
}
func (m *SObjMethodInvokeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SObjMethodInvokeRequest.Marshal(b, m, deterministic)
}
func (dst *SObjMethodInvokeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SObjMethodInvokeRequest.Merge(dst, src)
}
func (m *SObjMethodInvokeRequest) XXX_Size() int {
	return xxx_messageInfo_SObjMethodInvokeRequest.Size(m)
}
func (m *SObjMethodInvokeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SObjMethodInvokeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SObjMethodInvokeRequest proto.InternalMessageInfo

func (m *SObjMethodInvokeRequest) GetSObjId() string {
	if m != nil {
		return m.SObjId
	}
	return ""
}

func (m *SObjMethodInvokeRequest) GetSObjReplicaId() string {
	if m != nil {
		return m.SObjReplicaId
	}
	return ""
}

func (m *SObjMethodInvokeRequest) GetSObjMethodName() string {
	if m != nil {
		return m.SObjMethodName
	}
	return ""
}

func (m *SObjMethodInvokeRequest) GetSObjMethodParams() []byte {
	if m != nil {
		return m.SObjMethodParams
	}
	return nil
}

type SObjMethodInvokeResponse struct {
	SObjMethodResponse   []byte   `protobuf:"bytes,1,opt,name=sObjMethodResponse,proto3" json:"sObjMethodResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SObjMethodInvokeResponse) Reset()         { *m = SObjMethodInvokeResponse{} }
func (m *SObjMethodInvokeResponse) String() string { return proto.CompactTextString(m) }
func (*SObjMethodInvokeResponse) ProtoMessage()    {}
func (*SObjMethodInvokeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_RuntimeApiToKernelServer_f28af194d1f8932e, []int{6}
}
func (m *SObjMethodInvokeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SObjMethodInvokeResponse.Unmarshal(m, b)
}
func (m *SObjMethodInvokeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SObjMethodInvokeResponse.Marshal(b, m, deterministic)
}
func (dst *SObjMethodInvokeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SObjMethodInvokeResponse.Merge(dst, src)
}
func (m *SObjMethodInvokeResponse) XXX_Size() int {
	return xxx_messageInfo_SObjMethodInvokeResponse.Size(m)
}
func (m *SObjMethodInvokeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SObjMethodInvokeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SObjMethodInvokeResponse proto.InternalMessageInfo

func (m *SObjMethodInvokeResponse) GetSObjMethodResponse() []byte {
	if m != nil {
		return m.SObjMethodResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateSObjReplicaRequest)(nil), "sapphire.runtime.kernel.CreateSObjReplicaRequest")
	proto.RegisterType((*DMInfo)(nil), "sapphire.runtime.kernel.DMInfo")
	proto.RegisterType((*CreateSObjReplicaResponse)(nil), "sapphire.runtime.kernel.CreateSObjReplicaResponse")
	proto.RegisterType((*DeleteSObjReplicaRequest)(nil), "sapphire.runtime.kernel.DeleteSObjReplicaRequest")
	proto.RegisterType((*DeleteSObjReplicaResponse)(nil), "sapphire.runtime.kernel.DeleteSObjReplicaResponse")
	proto.RegisterType((*SObjMethodInvokeRequest)(nil), "sapphire.runtime.kernel.SObjMethodInvokeRequest")
	proto.RegisterType((*SObjMethodInvokeResponse)(nil), "sapphire.runtime.kernel.SObjMethodInvokeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KernelServiceClient is the client API for KernelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KernelServiceClient interface {
	CreateSObjReplica(ctx context.Context, in *CreateSObjReplicaRequest, opts ...grpc.CallOption) (*CreateSObjReplicaResponse, error)
	DeleteSObjReplica(ctx context.Context, in *DeleteSObjReplicaRequest, opts ...grpc.CallOption) (*DeleteSObjReplicaResponse, error)
	SObjMethodInvoke(ctx context.Context, in *SObjMethodInvokeRequest, opts ...grpc.CallOption) (*SObjMethodInvokeResponse, error)
}

type kernelServiceClient struct {
	cc *grpc.ClientConn
}

func NewKernelServiceClient(cc *grpc.ClientConn) KernelServiceClient {
	return &kernelServiceClient{cc}
}

func (c *kernelServiceClient) CreateSObjReplica(ctx context.Context, in *CreateSObjReplicaRequest, opts ...grpc.CallOption) (*CreateSObjReplicaResponse, error) {
	out := new(CreateSObjReplicaResponse)
	err := c.cc.Invoke(ctx, "/sapphire.runtime.kernel.KernelService/CreateSObjReplica", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) DeleteSObjReplica(ctx context.Context, in *DeleteSObjReplicaRequest, opts ...grpc.CallOption) (*DeleteSObjReplicaResponse, error) {
	out := new(DeleteSObjReplicaResponse)
	err := c.cc.Invoke(ctx, "/sapphire.runtime.kernel.KernelService/DeleteSObjReplica", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) SObjMethodInvoke(ctx context.Context, in *SObjMethodInvokeRequest, opts ...grpc.CallOption) (*SObjMethodInvokeResponse, error) {
	out := new(SObjMethodInvokeResponse)
	err := c.cc.Invoke(ctx, "/sapphire.runtime.kernel.KernelService/SObjMethodInvoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KernelServiceServer is the server API for KernelService service.
type KernelServiceServer interface {
	CreateSObjReplica(context.Context, *CreateSObjReplicaRequest) (*CreateSObjReplicaResponse, error)
	DeleteSObjReplica(context.Context, *DeleteSObjReplicaRequest) (*DeleteSObjReplicaResponse, error)
	SObjMethodInvoke(context.Context, *SObjMethodInvokeRequest) (*SObjMethodInvokeResponse, error)
}

func RegisterKernelServiceServer(s *grpc.Server, srv KernelServiceServer) {
	s.RegisterService(&_KernelService_serviceDesc, srv)
}

func _KernelService_CreateSObjReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSObjReplicaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).CreateSObjReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sapphire.runtime.kernel.KernelService/CreateSObjReplica",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).CreateSObjReplica(ctx, req.(*CreateSObjReplicaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_DeleteSObjReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSObjReplicaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).DeleteSObjReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sapphire.runtime.kernel.KernelService/DeleteSObjReplica",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).DeleteSObjReplica(ctx, req.(*DeleteSObjReplicaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_SObjMethodInvoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SObjMethodInvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).SObjMethodInvoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sapphire.runtime.kernel.KernelService/SObjMethodInvoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).SObjMethodInvoke(ctx, req.(*SObjMethodInvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KernelService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sapphire.runtime.kernel.KernelService",
	HandlerType: (*KernelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSObjReplica",
			Handler:    _KernelService_CreateSObjReplica_Handler,
		},
		{
			MethodName: "DeleteSObjReplica",
			Handler:    _KernelService_DeleteSObjReplica_Handler,
		},
		{
			MethodName: "SObjMethodInvoke",
			Handler:    _KernelService_SObjMethodInvoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "RuntimeApiToKernelServer.proto",
}

func init() {
	proto.RegisterFile("RuntimeApiToKernelServer.proto", fileDescriptor_RuntimeApiToKernelServer_f28af194d1f8932e)
}

var fileDescriptor_RuntimeApiToKernelServer_f28af194d1f8932e = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0x5e, 0xda, 0xd1, 0x8d, 0xb7, 0x0d, 0x6d, 0x0f, 0xc1, 0xb2, 0x1e, 0xa0, 0xb2, 0x26, 0x34,
	0x21, 0x14, 0x6d, 0x1d, 0x77, 0xc4, 0xb6, 0x4b, 0x41, 0xa3, 0x55, 0xc6, 0x81, 0x6b, 0x9a, 0x3e,
	0x58, 0xba, 0x34, 0x0e, 0xb6, 0x33, 0x69, 0x12, 0x67, 0x0e, 0xfc, 0x2b, 0xdc, 0xf9, 0xfb, 0x50,
	0x1c, 0x77, 0xfd, 0x11, 0xbb, 0xd2, 0xa4, 0xdd, 0xe2, 0xef, 0x7d, 0x7e, 0xef, 0xb3, 0xbf, 0x2f,
	0x86, 0x57, 0x61, 0x91, 0xa9, 0x64, 0x42, 0x1f, 0xf3, 0xe4, 0x2b, 0xff, 0x4c, 0x22, 0xa3, 0xf4,
	0x8a, 0xc4, 0x2d, 0x89, 0x20, 0x17, 0x5c, 0x71, 0xdc, 0x97, 0x51, 0x9e, 0x5f, 0x27, 0x82, 0x02,
	0x51, 0x11, 0x83, 0x1b, 0x4d, 0x62, 0xff, 0x1a, 0xe0, 0x9f, 0x0b, 0x8a, 0x14, 0x5d, 0xf5, 0x87,
	0xe3, 0x90, 0xf2, 0x34, 0x89, 0xa3, 0x90, 0x7e, 0x16, 0x24, 0x15, 0xb6, 0x61, 0x53, 0xf6, 0x87,
	0xe3, 0x2f, 0xd1, 0x84, 0x7c, 0xaf, 0xe3, 0x1d, 0x3d, 0x0d, 0xef, 0xd7, 0x78, 0x0c, 0xcf, 0xcb,
	0xef, 0x73, 0x9e, 0x49, 0x25, 0x8a, 0x58, 0x71, 0xa1, 0x69, 0x0d, 0x4d, 0xb3, 0x95, 0xf0, 0x3d,
	0xbc, 0x58, 0x82, 0x07, 0x91, 0x88, 0x26, 0xd2, 0x6f, 0x76, 0xbc, 0xa3, 0xed, 0xd0, 0x5e, 0xc4,
	0xb7, 0xb0, 0x5b, 0x16, 0x06, 0x91, 0xa0, 0x4c, 0x95, 0x1a, 0x7b, 0x23, 0x7f, 0x5d, 0x0f, 0xa9,
	0xe1, 0xf8, 0x12, 0x5a, 0xb2, 0x62, 0x3c, 0xd1, 0x0c, 0xb3, 0xc2, 0x43, 0xd8, 0x91, 0xb3, 0xd3,
	0xf5, 0x46, 0x7e, 0x4b, 0x97, 0x17, 0x41, 0x7c, 0x07, 0x7b, 0x73, 0x40, 0x7f, 0x38, 0xa6, 0x58,
	0xf9, 0x1b, 0x5a, 0x5b, 0xbd, 0xc0, 0x04, 0xb4, 0x2e, 0x2e, 0x7b, 0xd9, 0x77, 0x8e, 0x0c, 0xb6,
	0xe3, 0x34, 0xa1, 0x4c, 0x0d, 0x78, 0x9a, 0xc4, 0x77, 0xe6, 0xa6, 0x16, 0xb0, 0x92, 0x23, 0xb5,
	0x1f, 0x86, 0x53, 0x5d, 0xd3, 0x02, 0x86, 0x1d, 0xd8, 0xfa, 0x21, 0x78, 0x91, 0x1b, 0x4a, 0x53,
	0x53, 0xe6, 0x21, 0xf6, 0xc7, 0x83, 0x03, 0x8b, 0x59, 0x32, 0xe7, 0x99, 0x24, 0xbb, 0x7e, 0xcf,
	0xa1, 0x1f, 0x3f, 0x00, 0x94, 0x60, 0x75, 0x06, 0xad, 0x67, 0xab, 0xfb, 0x3a, 0x70, 0xc4, 0x24,
	0xa8, 0x68, 0xe1, 0xdc, 0x16, 0xf6, 0x0d, 0xfc, 0x0b, 0x4a, 0xc9, 0x1a, 0x9c, 0x99, 0x11, 0xde,
	0x6a, 0x23, 0x1a, 0x16, 0x23, 0xd8, 0x29, 0x1c, 0x58, 0x3a, 0x9b, 0x53, 0x96, 0xad, 0x55, 0xa4,
	0x0a, 0xa9, 0x5b, 0x6f, 0x86, 0x66, 0xc5, 0xfe, 0x7a, 0xb0, 0x5f, 0xf2, 0x2f, 0x49, 0x5d, 0xf3,
	0x51, 0x2f, 0xbb, 0xe5, 0x37, 0xf4, 0x28, 0x72, 0xf0, 0x0d, 0x3c, 0x93, 0xf7, 0x8d, 0x75, 0xc8,
	0x2b, 0x6b, 0x96, 0xd0, 0x69, 0x52, 0x2b, 0xc4, 0x44, 0x7b, 0x5d, 0x5f, 0x7f, 0x0d, 0x67, 0x9f,
	0xc0, 0xaf, 0x8b, 0x35, 0x27, 0x0c, 0x00, 0x67, 0xfc, 0x29, 0x6a, 0x8c, 0xb4, 0x54, 0xba, 0xbf,
	0x9b, 0xb0, 0x33, 0xfb, 0xe5, 0x93, 0x98, 0xf0, 0x17, 0xec, 0xd5, 0x62, 0x82, 0x27, 0x4e, 0x73,
	0x5d, 0xff, 0x7f, 0xbb, 0xfb, 0x90, 0x2d, 0x95, 0x1a, 0xb6, 0x56, 0x4e, 0xaf, 0xd9, 0xb7, 0x62,
	0xba, 0x2b, 0x44, 0x2b, 0xa6, 0x3b, 0xd3, 0xc1, 0xd6, 0xf0, 0x0e, 0x76, 0x97, 0x6f, 0x16, 0x8f,
	0x9d, 0x9d, 0x1c, 0x89, 0x69, 0x9f, 0x3c, 0x60, 0xc7, 0x74, 0xf4, 0xd9, 0x21, 0xb8, 0x9e, 0xd9,
	0xb3, 0x0d, 0x63, 0xcd, 0xc0, 0x1b, 0xb6, 0xf4, 0x8b, 0x7c, 0xfa, 0x3f, 0x00, 0x00, 0xff, 0xff,
	0xe7, 0xd1, 0x4c, 0x6b, 0xb3, 0x05, 0x00, 0x00,
}
