// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RuntimeApiToKernelServer.proto

package sapphire.runtime.kernel;

public interface CreateSObjReplicaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RuntimeApiToKernelServer.CreateSObjReplicaResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional bytes sObjReplicaObject = 1;</code>
   */
  com.google.protobuf.ByteString getSObjReplicaObject();

  /**
   * <code>optional .RuntimeApiToKernelServer.DMInfo sObjDMInfo = 2;</code>
   */
  boolean hasSObjDMInfo();
  /**
   * <code>optional .RuntimeApiToKernelServer.DMInfo sObjDMInfo = 2;</code>
   */
  sapphire.runtime.kernel.DMInfo getSObjDMInfo();
}
