// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RuntimeApiToKernelServer.proto

package sapphire.runtime.kernel;

/**
 * Protobuf type {@code RuntimeApiToKernelServer.CreateSObjReplicaResponse}
 */
public  final class CreateSObjReplicaResponse extends
    com.google.protobuf.GeneratedMessageLite<
        CreateSObjReplicaResponse, CreateSObjReplicaResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:RuntimeApiToKernelServer.CreateSObjReplicaResponse)
    CreateSObjReplicaResponseOrBuilder {
  private CreateSObjReplicaResponse() {
    sObjReplicaObject_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int SOBJREPLICAOBJECT_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString sObjReplicaObject_;
  /**
   * <code>optional bytes sObjReplicaObject = 1;</code>
   */
  public com.google.protobuf.ByteString getSObjReplicaObject() {
    return sObjReplicaObject_;
  }
  /**
   * <code>optional bytes sObjReplicaObject = 1;</code>
   */
  private void setSObjReplicaObject(com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    sObjReplicaObject_ = value;
  }
  /**
   * <code>optional bytes sObjReplicaObject = 1;</code>
   */
  private void clearSObjReplicaObject() {
    
    sObjReplicaObject_ = getDefaultInstance().getSObjReplicaObject();
  }

  public static final int SOBJDMINFO_FIELD_NUMBER = 2;
  private sapphire.runtime.kernel.DMInfo sObjDMInfo_;
  /**
   * <code>optional .RuntimeApiToKernelServer.DMInfo sObjDMInfo = 2;</code>
   */
  public boolean hasSObjDMInfo() {
    return sObjDMInfo_ != null;
  }
  /**
   * <code>optional .RuntimeApiToKernelServer.DMInfo sObjDMInfo = 2;</code>
   */
  public sapphire.runtime.kernel.DMInfo getSObjDMInfo() {
    return sObjDMInfo_ == null ? sapphire.runtime.kernel.DMInfo.getDefaultInstance() : sObjDMInfo_;
  }
  /**
   * <code>optional .RuntimeApiToKernelServer.DMInfo sObjDMInfo = 2;</code>
   */
  private void setSObjDMInfo(sapphire.runtime.kernel.DMInfo value) {
    if (value == null) {
      throw new NullPointerException();
    }
    sObjDMInfo_ = value;
    
    }
  /**
   * <code>optional .RuntimeApiToKernelServer.DMInfo sObjDMInfo = 2;</code>
   */
  private void setSObjDMInfo(
      sapphire.runtime.kernel.DMInfo.Builder builderForValue) {
    sObjDMInfo_ = builderForValue.build();
    
  }
  /**
   * <code>optional .RuntimeApiToKernelServer.DMInfo sObjDMInfo = 2;</code>
   */
  private void mergeSObjDMInfo(sapphire.runtime.kernel.DMInfo value) {
    if (sObjDMInfo_ != null &&
        sObjDMInfo_ != sapphire.runtime.kernel.DMInfo.getDefaultInstance()) {
      sObjDMInfo_ =
        sapphire.runtime.kernel.DMInfo.newBuilder(sObjDMInfo_).mergeFrom(value).buildPartial();
    } else {
      sObjDMInfo_ = value;
    }
    
  }
  /**
   * <code>optional .RuntimeApiToKernelServer.DMInfo sObjDMInfo = 2;</code>
   */
  private void clearSObjDMInfo() {  sObjDMInfo_ = null;
    
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!sObjReplicaObject_.isEmpty()) {
      output.writeBytes(1, sObjReplicaObject_);
    }
    if (sObjDMInfo_ != null) {
      output.writeMessage(2, getSObjDMInfo());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!sObjReplicaObject_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, sObjReplicaObject_);
    }
    if (sObjDMInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSObjDMInfo());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static sapphire.runtime.kernel.CreateSObjReplicaResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.runtime.kernel.CreateSObjReplicaResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.runtime.kernel.CreateSObjReplicaResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static sapphire.runtime.kernel.CreateSObjReplicaResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static sapphire.runtime.kernel.CreateSObjReplicaResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.runtime.kernel.CreateSObjReplicaResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.runtime.kernel.CreateSObjReplicaResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static sapphire.runtime.kernel.CreateSObjReplicaResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static sapphire.runtime.kernel.CreateSObjReplicaResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static sapphire.runtime.kernel.CreateSObjReplicaResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sapphire.runtime.kernel.CreateSObjReplicaResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code RuntimeApiToKernelServer.CreateSObjReplicaResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        sapphire.runtime.kernel.CreateSObjReplicaResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:RuntimeApiToKernelServer.CreateSObjReplicaResponse)
      sapphire.runtime.kernel.CreateSObjReplicaResponseOrBuilder {
    // Construct using sapphire.runtime.RuntimeApiToKernelServer.CreateSObjReplicaResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional bytes sObjReplicaObject = 1;</code>
     */
    public com.google.protobuf.ByteString getSObjReplicaObject() {
      return instance.getSObjReplicaObject();
    }
    /**
     * <code>optional bytes sObjReplicaObject = 1;</code>
     */
    public Builder setSObjReplicaObject(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSObjReplicaObject(value);
      return this;
    }
    /**
     * <code>optional bytes sObjReplicaObject = 1;</code>
     */
    public Builder clearSObjReplicaObject() {
      copyOnWrite();
      instance.clearSObjReplicaObject();
      return this;
    }

    /**
     * <code>optional .RuntimeApiToKernelServer.DMInfo sObjDMInfo = 2;</code>
     */
    public boolean hasSObjDMInfo() {
      return instance.hasSObjDMInfo();
    }
    /**
     * <code>optional .RuntimeApiToKernelServer.DMInfo sObjDMInfo = 2;</code>
     */
    public sapphire.runtime.kernel.DMInfo getSObjDMInfo() {
      return instance.getSObjDMInfo();
    }
    /**
     * <code>optional .RuntimeApiToKernelServer.DMInfo sObjDMInfo = 2;</code>
     */
    public Builder setSObjDMInfo(sapphire.runtime.kernel.DMInfo value) {
      copyOnWrite();
      instance.setSObjDMInfo(value);
      return this;
      }
    /**
     * <code>optional .RuntimeApiToKernelServer.DMInfo sObjDMInfo = 2;</code>
     */
    public Builder setSObjDMInfo(
        sapphire.runtime.kernel.DMInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setSObjDMInfo(builderForValue);
      return this;
    }
    /**
     * <code>optional .RuntimeApiToKernelServer.DMInfo sObjDMInfo = 2;</code>
     */
    public Builder mergeSObjDMInfo(sapphire.runtime.kernel.DMInfo value) {
      copyOnWrite();
      instance.mergeSObjDMInfo(value);
      return this;
    }
    /**
     * <code>optional .RuntimeApiToKernelServer.DMInfo sObjDMInfo = 2;</code>
     */
    public Builder clearSObjDMInfo() {  copyOnWrite();
      instance.clearSObjDMInfo();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:RuntimeApiToKernelServer.CreateSObjReplicaResponse)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new sapphire.runtime.kernel.CreateSObjReplicaResponse();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        sapphire.runtime.kernel.CreateSObjReplicaResponse other = (sapphire.runtime.kernel.CreateSObjReplicaResponse) arg1;
        sObjReplicaObject_ = visitor.visitByteString(sObjReplicaObject_ != com.google.protobuf.ByteString.EMPTY, sObjReplicaObject_,
            other.sObjReplicaObject_ != com.google.protobuf.ByteString.EMPTY, other.sObjReplicaObject_);
        sObjDMInfo_ = visitor.visitMessage(sObjDMInfo_, other.sObjDMInfo_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {

                sObjReplicaObject_ = input.readBytes();
                break;
              }
              case 18: {
                sapphire.runtime.kernel.DMInfo.Builder subBuilder = null;
                if (sObjDMInfo_ != null) {
                  subBuilder = sObjDMInfo_.toBuilder();
                }
                sObjDMInfo_ = input.readMessage(sapphire.runtime.kernel.DMInfo.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(sObjDMInfo_);
                  sObjDMInfo_ = subBuilder.buildPartial();
                }

                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (sapphire.runtime.kernel.CreateSObjReplicaResponse.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:RuntimeApiToKernelServer.CreateSObjReplicaResponse)
  private static final sapphire.runtime.kernel.CreateSObjReplicaResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CreateSObjReplicaResponse();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static sapphire.runtime.kernel.CreateSObjReplicaResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CreateSObjReplicaResponse> PARSER;

  public static com.google.protobuf.Parser<CreateSObjReplicaResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

