// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RuntimeApiToKernelServer.proto

package sapphire.runtime.kernel;

public interface DeleteSObjReplicaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sapphire.runtime.kernel.DeleteSObjReplicaResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional bool status = 1;</code>
   */
  boolean getStatus();
}
