// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RuntimeApiToKernelServer.proto

package sapphire.runtime.kernel;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
