// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RuntimeApiToKernelServer.proto

package sapphire.runtime.kernel;

public interface SObjMethodInvokeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sapphire.runtime.kernel.SObjMethodInvokeResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional bytes sObjMethodResponse = 1;</code>
   */
  com.google.protobuf.ByteString getSObjMethodResponse();
}
